/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.AlmacenJpaController;
import Controladores.ComprasJpaController;
import Controladores.LocalizacionJpaController;
import Controladores.PrecioJpaController;
import Controladores.ProductoJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Almacen;
import Entidades.Compras;
import Entidades.Detalle_Compra;
import Entidades.Localizacion;
import Entidades.Precio;
import Entidades.Producto;
import Entidades.Proveedor;
import Facade.FacadeAlmacen;
import Facade.FacadeLocalizacion;
import Facade.FacadeProducto;
import Facade.FacadeProveedor;
import static Vistas.JfVenta.venta;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class jfComprasProveedor extends javax.swing.JFrame {
    Proveedor proveedor;
    Almacen productoAlmacen; 
    Compras compra;
   DefaultTableModel modelo2= new DefaultTableModel();
    //Variable para saber si debe Actualizar Precio
    int apc=0;
    /**
     * Creates new form jfComprasProveedor
     */
    public jfComprasProveedor() {
        initComponents();
         setLocationRelativeTo(null);
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Proveedor:");

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Direccion:");

        jLabel3.setText("CUIT:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("E-Mail:");

        jButton7.setText("+");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel14.setText("/");

        jLabel15.setText("/");

        jLabel16.setText("Fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton7)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setText("Producto:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tabla de Productos:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Nombre del Producto:");

        jLabel10.setText("Codigo:");

        jLabel11.setText("Cantidad a comprar:");

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jButton4.setText("Quitar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel17.setText("Nuevo precio:");

        jButton9.setText("Actualizar Precio");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField14))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jLabel12.setText("Lista de Prodcutos a Comprar:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton6.setText("Volver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //llenar compras 
        if(Menu.opcion==1){
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
        Compras compras=new Compras();
        compras.setProveedor(proveedor);
        Calendar fecha = Calendar.getInstance();
                        int dia=Integer.parseInt(jTextField13.getText());
                        int mes=Integer.parseInt(jTextField12.getText());
                        int año=Integer.parseInt(jTextField11.getText());
                        fecha.set(año, mes-1, dia);
                        Date fec=(Date)fecha.getTime();
        compras.setFecha(fec);
        compras.setPrecio_totol(Float.parseFloat(jTextField10.getText()));
        compras.setAnulacion("NO");
        compras.setUsu(JLogin.usu);
        //Detalle Compras
        /// cargar detalle de Venta
        ArrayList<Detalle_Compra> ldc = new ArrayList<Detalle_Compra>();
        for(int i=0; i< jTable2.getRowCount(); i++ ){
        Detalle_Compra dc=new Detalle_Compra();    
        List<Producto> lp=new FacadeProducto().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
        dc.setProducto(lp.get(0));
        dc.setCantidad(Integer.parseInt(jTable2.getValueAt(i, 4).toString()));
        dc.setPrecio(Float.valueOf(jTable2.getValueAt(i, 3).toString()));
        ldc.add(dc);
        }
        compras.setDetalle_compra(ldc);
        ComprasJpaController cjc=new ComprasJpaController(emf);
        cjc.create(compras);
        //Actualizar el Almacen con los productos ingresados
         // Modificar Almacen
        for(int i=0; i< jTable2.getRowCount(); i++ ){
            try {
                Almacen almacen= new Almacen();
                List<Almacen> la=new FacadeAlmacen().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
                almacen=la.get(0);
                float cantalmacen=Float.parseFloat(la.get(0).getCantidad());
                float cantcomprada=Float.parseFloat(jTable2.getValueAt(i, 4).toString());
                almacen.setProducto(la.get(0).getProducto());
                almacen.setCantidad(String.valueOf(cantalmacen+cantcomprada));
                almacen.setAlerta(la.get(0).getAlerta());
                almacen.setLocalizacion(la.get(0).getLocalizacion());
                AlmacenJpaController ajp=new AlmacenJpaController(emf);
                ajp.edit(almacen);
                
             //Actualizo la unidades en la localizacion primera
            List<Localizacion> lista=new FacadeLocalizacion().buscarxAlmacen(String.valueOf(almacen.getId()),String.valueOf(la.get(0).getProducto().getId()));
            Localizacion loca=lista.get(0);
            System.out.println(loca.getDescripcion());
            float cantidad=loca.getCantidad();
            float cantrepo=Integer.parseInt(jTable2.getValueAt(i, 4).toString());
            loca.setCantidad(cantidad+cantrepo);
            LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
            ljc.edit(loca);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
        JOptionPane.showMessageDialog(rootPane, "La operacion se realizo con exito");
        jButton5.setEnabled(false);
    }
         if(Menu.opcion==2){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                Compras compras=compra;
                compras.setProveedor(proveedor);
                Calendar fecha = Calendar.getInstance();
                                int dia=Integer.parseInt(jTextField13.getText());
                                int mes=Integer.parseInt(jTextField12.getText());
                                int año=Integer.parseInt(jTextField11.getText());
                                fecha.set(año, mes-1, dia);
                                Date fec=(Date)fecha.getTime();
                compras.setFecha(fec);
                compras.setPrecio_totol(Float.parseFloat(jTextField10.getText()));
                compras.setAnulacion("SI");
                //Detalle Compras
                /// cargar detalle de Venta
                ArrayList<Detalle_Compra> ldc = new ArrayList<Detalle_Compra>();
                for(int i=0; i< jTable2.getRowCount(); i++ ){
                Detalle_Compra dc=new Detalle_Compra();    
                List<Producto> lp=new FacadeProducto().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
                dc.setProducto(lp.get(0));
                dc.setCantidad(Integer.parseInt(jTable2.getValueAt(i, 4).toString()));
                dc.setPrecio(Float.valueOf(jTable2.getValueAt(i, 3).toString()));
                ldc.add(dc);
                }
                compras.setDetalle_compra(ldc);
                ComprasJpaController cjc=new ComprasJpaController(emf);
                cjc.edit(compras);
                //Actualizar el Almacen con los productos ingresados
                 // Modificar Almacen
                for(int i=0; i< jTable2.getRowCount(); i++ ){
                    try {
                        Almacen almacen= new Almacen();
                        List<Almacen> la=new FacadeAlmacen().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
                        almacen=la.get(0);
                        float cantalmacen=Float.parseFloat(la.get(0).getCantidad());
                        float cantcomprada=Float.parseFloat(jTable2.getValueAt(i, 4).toString());
                        almacen.setProducto(la.get(0).getProducto());
                        almacen.setCantidad(String.valueOf(cantalmacen-cantcomprada));
                        almacen.setAlerta(la.get(0).getAlerta());
                        almacen.setLocalizacion(la.get(0).getLocalizacion());
                        AlmacenJpaController ajp=new AlmacenJpaController(emf);
                        ajp.edit(almacen);
                        
                        //Actualizo la unidades en la localizacion primera
                        List<Localizacion> lista=new FacadeLocalizacion().buscarxAlmacen(String.valueOf(la.get(0).getId()),String.valueOf(la.get(0).getProducto().getId()));
                        Localizacion loca=lista.get(0);
                        System.out.println(loca.getDescripcion());
                        float cantidad=loca.getCantidad();
                        float cantcompra=Integer.parseInt(jTable2.getValueAt(i, 4).toString());
                        loca.setCantidad(cantidad-cantcompra);
                        LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                        ljc.edit(loca);
                    } catch (NonexistentEntityException ex) {
                        Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                JOptionPane.showMessageDialog(rootPane, "La operacion se realizo con exito");
                jButton5.setEnabled(false);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(jfComprasProveedor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(jfComprasProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
       List<Proveedor> prove=new FacadeProveedor().buscarxnombre(jComboBox1.getSelectedItem().toString());
       proveedor=prove.get(0);
       jTextField1.setText(proveedor.getDireccion());
       jTextField2.setText(proveedor.getCuit());
       jTextField3.setText(proveedor.getTel());
       jTextField4.setText(proveedor.getEmail());
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         List<Proveedor> prove=new FacadeProveedor().buscarxnombre(jComboBox1.getSelectedItem().toString());
       proveedor=prove.get(0);
       jTextField1.setText(proveedor.getDireccion());
       jTextField2.setText(proveedor.getCuit());
       jTextField3.setText(proveedor.getTel());
       jTextField4.setText(proveedor.getEmail());
       llenarTablaProd();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JfProveedor ventana=new JfProveedor();
        ventana.setVisible(true);
        inicializarComboProveedor();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(!jTextField5.getText().equals("")){
        buscarProducto();
        }
         if(jTextField5.getText().equals("")){
         llenarTablaProd();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(!jTextField6.getText().equals("")){
        buscarProductoxCod();
        }
        if(jTextField6.getText().equals("")){
        llenarTablaProd();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           if(jTable1.getSelectedRow()!=-1){
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      productoAlmacen=new AlmacenJpaController(emf).findAlmacen(valor);
      jTextField8.setText(productoAlmacen.getProducto().getCod());
      jTextField7.setText(String.valueOf(productoAlmacen.getProducto().getDescripcion()));
      
           }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!jTextField9.getText().equals("")){
            try {
                float precioproductocompra=0;
                Vector vector=new Vector();
                vector.add(productoAlmacen.getId());
                vector.add(productoAlmacen.getProducto().getDescripcion());
                vector.add(productoAlmacen.getProducto().getProveedor().getNombre());
                if(apc==0){
                    vector.add(productoAlmacen.getProducto().getPrecio().getPrecio_real());
                    precioproductocompra=productoAlmacen.getProducto().getPrecio().getPrecio_real();
                }
                if(apc==1){
                    vector.add(Float.parseFloat(jTextField14.getText()));
                    precioproductocompra=Float.parseFloat(jTextField14.getText());
                }
                vector.add(jTextField9.getText());
                modelo2.addRow(vector);
                jTable2.setModel(modelo2);
                calcularTotal();
                jButton5.setEnabled(true);
                
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                PrecioJpaController pjc=new PrecioJpaController(emf);
                Precio precio=productoAlmacen.getProducto().getPrecio();
                precio.setPrecio_real(precioproductocompra);
                pjc.edit(precio);
                limpiarCampos();
            } catch (Exception ex) {
                Logger.getLogger(jfComprasProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "debe completar el campo: Cantidad a comprar ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int index=jTable2.getSelectedRow();
       modelo2.removeRow(index);
       jTable2.setModel(modelo2);
       calcularTotal();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Menu.opcion=1;
        JfProducto ventana=new JfProducto();
        ventana.setVisible(true);
        llenarTablaProd();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        apc=1;
        jTextField14.setEnabled(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField14KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfComprasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfComprasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfComprasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfComprasProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfComprasProveedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
    if(Menu.opcion==1){    
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(true);
    jTextField6.setEnabled(true);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(true);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
    jTextField14.setEnabled(false);
    jComboBox1.setEnabled(true);
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);
    jButton5.setEnabled(false);
    jButton6.setEnabled(true);
    jButton9.setEnabled(true);
    inicializarComboProveedor();
    inicializarTabal1();
    inicializarTabla2();
    establecerFecha();
     }
    if(Menu.opcion==2){
      jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
    jTextField14.setEnabled(false);
    jComboBox1.setEnabled(false);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(true);
    jButton6.setEnabled(true);
     jButton9.setEnabled(true);
    jButton8.setEnabled(false);
    jTable1.setEnabled(false);
    inicializarComboProveedor();
    inicializarTabal1();
    inicializarTabla2();
    establecerFecha();
    BuscarCompra ventana= new BuscarCompra(this, true);
    ventana.setVisible(true);
    compra=ventana.compra;
    LlenarCamposCompra();
    }
    if(Menu.opcion==4){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
    jTextField14.setEnabled(false);
    jComboBox1.setEnabled(false);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(true);
    jButton6.setEnabled(true);
    jButton8.setEnabled(false);
     jButton9.setEnabled(false);
    jTable1.setEnabled(false);
    inicializarComboProveedor();
    inicializarTabal1();
    inicializarTabla2();
    establecerFecha();
    BuscarCompraGenerica ventana= new BuscarCompraGenerica(this, true);
    ventana.setVisible(true);
    compra=ventana.compra;
    LlenarCamposCompra();
    }
    if(Menu.opcion==5){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
    jComboBox1.setEnabled(false);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(true);
    jButton6.setEnabled(true);
    jButton8.setEnabled(false);
    jTable1.setEnabled(false);
    inicializarComboProveedor();
    inicializarTabal1();
    inicializarTabla2();
    establecerFecha();
    //BuscarCompraGenerica ventana= new BuscarCompraGenerica(this, true);
    //ventana.setVisible(true);
    compra=Caja.compra;
    LlenarCamposCompra();
    }
    }

    private void inicializarComboProveedor() {
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
     List<Proveedor> lista;
     lista=new FacadeProveedor().listar();
     if(lista.get(0).getId()!=null){
      for(int i=0;  i < lista.size(); i++){
      Vector vector = new Vector();
      vector.add(lista.get(i).getNombre());
      modeloCombo.addElement(lista.get(i).getNombre());
     }
     jComboBox1.setModel(modeloCombo);            
    }  
    }
     public void llenarTablaProd(){
    EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
    List <Producto> listap=new FacadeProducto().buscarxProveedor(jComboBox1.getSelectedItem().toString());
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("Codigo");
    modelo.addColumn("Producto");
    modelo.addColumn("Proveedor");
    modelo.addColumn("precio Compra");
    modelo.addColumn("precio Venta");
    for(int i=0; i<listap.size(); i++){
    Vector vector=new Vector();
    vector.add(listap.get(i).getId());
    vector.add(listap.get(i).getCod());
    vector.add(listap.get(i).getDescripcion());
    vector.add(listap.get(i).getProveedor().getNombre());
    vector.add(listap.get(i).getPrecio().getPrecio_real());
    vector.add(listap.get(i).getPrecio().getPrecio_contado());    
    modelo.addRow(vector);
    }
    jTable1.setModel(modelo);
    }
     
      private void buscarProducto() {
       
    EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
    List <Producto> listap=new FacadeProducto().buscarxnombre(jTextField5.getText().toUpperCase(),proveedor.getNombre());
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("Codigo");
    modelo.addColumn("Producto");
    modelo.addColumn("Proveedor");
    modelo.addColumn("precio Compra");
    modelo.addColumn("precio Venta");
    for(int i=0; i<listap.size(); i++){
    Vector vector=new Vector();
    vector.add(listap.get(i).getId());
    vector.add(listap.get(i).getCod());
    vector.add(listap.get(i).getDescripcion());
    vector.add(listap.get(i).getProveedor().getNombre());
    vector.add(listap.get(i).getPrecio().getPrecio_real());
    vector.add(listap.get(i).getPrecio().getPrecio_contado());    
    modelo.addRow(vector);
    }
    jTable1.setModel(modelo);
    }

    private void buscarProductoxCod() {
     EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
    List <Producto> listap=new FacadeProducto().buscarxCod(jTextField6.getText().toUpperCase(), proveedor.getNombre());
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("Codigo");
    modelo.addColumn("Producto");
    modelo.addColumn("Proveedor");
    modelo.addColumn("precio Compra");
    modelo.addColumn("precio Venta");
    for(int i=0; i<listap.size(); i++){
    Vector vector=new Vector();
    vector.add(listap.get(i).getId());
    vector.add(listap.get(i).getCod());
    vector.add(listap.get(i).getDescripcion());
    vector.add(listap.get(i).getProveedor().getNombre());
    vector.add(listap.get(i).getPrecio().getPrecio_real());
    vector.add(listap.get(i).getPrecio().getPrecio_contado());    
    modelo.addRow(vector);
    }
    jTable1.setModel(modelo);   
    }
     public void inicializarTabla2(){
       modelo2.addColumn("Id");
       modelo2.addColumn("Producto");
       modelo2.addColumn("Proveedor");
       modelo2.addColumn("Precio de compra");
       modelo2.addColumn("Cantidad");
       jTable2.setModel(modelo2);
    }
      private void calcularTotal() {
    float total=0;    
    for(int i=0; i<jTable2.getRowCount();i++){
    float precio= Float.parseFloat(jTable2.getValueAt(i, 3).toString());
    float cantidad=Float.parseFloat(jTable2.getValueAt(i, 4).toString());
    float calculo= precio*cantidad;
    total=total+calculo;
    }
    jTextField10.setText(String.valueOf(total));
    }
        private void establecerFecha() {
        //Calendar fecha = Calendar.getInstance();
        Date d=new Date(); 
                int dia1=d.getDate();
                int mes1=d.getMonth()+1;
                int anio1=d.getYear()+1900;
               jTextField13.setText(String.valueOf(dia1));
               jTextField12.setText(String.valueOf(mes1));
               jTextField11.setText(String.valueOf(anio1));
    }

    private void LlenarCamposCompra() {
      Date d=compra.getFecha(); 
                int dia1=d.getDate();
                int mes1=d.getMonth()+1;
                int anio1=d.getYear()+1900;
               jTextField13.setText(String.valueOf(dia1));
               jTextField12.setText(String.valueOf(mes1));
               jTextField11.setText(String.valueOf(anio1));
               jComboBox1.setSelectedItem(compra.getProveedor().getNombre());
       List<Proveedor> prove=new FacadeProveedor().buscarxnombre(jComboBox1.getSelectedItem().toString());
       proveedor=prove.get(0);
       jTextField1.setText(proveedor.getDireccion());
       jTextField2.setText(proveedor.getCuit());
       jTextField3.setText(proveedor.getTel());
       jTextField4.setText(proveedor.getEmail());
        // Llenar Detalle de Compras
     for(int i=0; i < compra.getDetalle_compra().size(); i++){
       Vector vector=new Vector();  
       vector.add(compra.getDetalle_compra().get(i).getProducto().getId());
       vector.add(compra.getDetalle_compra().get(i).getProducto().getDescripcion());
       vector.add(compra.getDetalle_compra().get(i).getProducto().getProveedor().getNombre());
       vector.add(compra.getDetalle_compra().get(i).getProducto().getPrecio().getPrecio_contado());
       vector.add(compra.getDetalle_compra().get(i).getCantidad());
       modelo2.addRow(vector);
     }
     jTable2.setModel(modelo2);
     calcularTotal();
     
               
    }

    private void inicializarTabal1() {
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("Codigo");
    modelo.addColumn("Producto");
    modelo.addColumn("Proveedor");
    modelo.addColumn("precio Compra");
    modelo.addColumn("precio Venta");
    jTable1.setModel(modelo);
    }
    public void limpiarCampos(){
    jTextField9.setEnabled(false);
    jTextField14.setEnabled(false);
    }
}
