/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.AlmacenJpaController;
import Controladores.ContratoJpaController;
import Controladores.FiadoJpaController;
import Controladores.LocalizacionJpaController;
import Entidades.Almacen;
import Entidades.Cliente;
import Entidades.CuentaFiado;
import Entidades.Detalle_Contrato;
import Entidades.Fiado;
import Entidades.Localizacion;
import Entidades.Producto;
import Entidades.cuenta_contrato;
import Entidades.detalleFiado;
import Facade.FacadeAlmacen;
import Facade.FacadeLocalizacion;
import Facade.FacadeProducto;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo
 */
public class jfFiado extends javax.swing.JFrame {
     static int opcion=1;// variable que va a la pantalla cliente para agregar un cliente desde la venta
    Almacen productoAlmacen;
    DefaultTableModel modelo2=new DefaultTableModel();
    Cliente cliente;
    Fiado fiado;

    /**
     * Creates new form jfFiado
     */
    public jfFiado() {
        initComponents();
        inicializarComponenetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel2.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel4.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField2.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel5.text")); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField3.text")); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel6.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField4.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel7.text")); // NOI18N

        jTextField5.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField5.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel8.text")); // NOI18N

        jTextField6.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField6.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel9.text")); // NOI18N

        jTextField7.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField7.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel10.text")); // NOI18N

        jTextField8.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField8.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel11.text")); // NOI18N

        jTextField9.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField9.text")); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        jButton5.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel12.text")); // NOI18N

        jTextField10.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField10.text")); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton6.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton7.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jButton8.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jButton8.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel13.text")); // NOI18N

        jTextField11.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField11.text")); // NOI18N
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel14.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jLabel14.text")); // NOI18N

        jTextField12.setText(org.openide.util.NbBundle.getMessage(jfFiado.class, "jfFiado.jTextField12.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(329, 329, 329)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)
                            .addComponent(jLabel13)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        BuscarCliente ventana=new BuscarCliente(this, true);
        ventana.setVisible(true);
        cliente=ventana.cliente_filtrado;
        jTextField1.setText(cliente.getApellido() +" "+ cliente.getNombre());
        cargarTablaProducto();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!jTextField2.getText().equals("")){
        buscarProducto();
        }
        if(jTextField2.getText().equals("")){
        cargarTablaProducto();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(!jTextField3.getText().equals("")){
        buscarxcodigo();
        }
        if(jTextField3.getText().equals("")){
        cargarTablaProducto();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      if(jTable1.getSelectedRow()!=-1){
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      productoAlmacen=new AlmacenJpaController(emf).findAlmacen(valor);
      jTextField4.setText(productoAlmacen.getProducto().getDescripcion());
      jTextField5.setText(productoAlmacen.getProducto().getTalle());
      jTextField6.setText(productoAlmacen.getProducto().getProveedor().getNombre());
      jTextField7.setText(String.valueOf(productoAlmacen.getProducto().getPrecio().getPrecio_contado()));
      jTextField8.setText(String.valueOf(productoAlmacen.getCantidad()));
     
      
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          if(productoAlmacen!=null && !jTextField9.getText().equals("")){ 
       float unidadesDisponibles=Float.parseFloat(jTextField8.getText());
       float unidadesRequeridas=Float.parseFloat(jTextField9.getText());
       //int unidadesRequeridas=Integer.parseInt(jTextField6.getText());
       //int unidaesenArea=Integer.parseInt(jTextField9.getText());
        if(unidadesRequeridas <= unidadesDisponibles){
       //  if(unidadesRequeridas<unidaesenArea){
       //modelo3=new DefaultTableModel();
      
           
           
       Vector vector=new Vector();
       vector.add(productoAlmacen.getId());
       vector.add(productoAlmacen.getProducto().getDescripcion());
       vector.add(productoAlmacen.getProducto().getProveedor().getNombre());
       vector.add(productoAlmacen.getProducto().getPrecio().getPrecio_contado());
       vector.add(jTextField9.getText());
       modelo2.addRow(vector);
       jTable2.setModel(modelo2);
       limpiarCampos();
       calcularTotal();
        //}else{JOptionPane.showMessageDialog(rootPane, "Las unidades Requiridas son mayores a las disponible en esa Area");}
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Las unidades disponibles no cubren la demanda");
        }
         } else {JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un producto y especificar la cantidad a vender");
       }       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       int index=jTable2.getSelectedRow();
       modelo2.removeRow(index);
       jTable2.setModel(modelo2);
       limpiarCampos();
       calcularTotal();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(Menu.opcion==1){
        if(!jTextField1.getText().equals("") ){
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
            Fiado fiado=new Fiado();
            float anticipo=0;
            if(!jTextField11.getText().equals("")){
              fiado.setAnticipo(Float.parseFloat(jTextField11.getText())); 
              anticipo=Float.parseFloat(jTextField11.getText());
            }else{
             jTextField11.setText("0");
             fiado.setAnticipo(0);
             anticipo=0;
            }
            fiado.setAnulado("NO");
            fiado.setFecha(jXDatePicker1.getDate());
            fiado.setMonto(Float.parseFloat(jTextField10.getText()));
            fiado.setNombrefiador(jTextField1.getText().toUpperCase());
            float saldo=Float.parseFloat(jTextField10.getText())-anticipo;
            fiado.setSaldo(saldo);
            fiado.setEstado("EN TRAMITE");
            fiado.setUsu(JLogin.usu);
            
             /// cargar detalle de Venta
        ArrayList<detalleFiado> ldv = new ArrayList<detalleFiado>();
        for(int i=0; i< jTable2.getRowCount(); i++ ){
        detalleFiado dv=new detalleFiado();    
        List<Producto> lp=new FacadeProducto().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
        dv.setProducto(lp.get(0));
        dv.setCantidad(Integer.parseInt(jTable2.getValueAt(i, 4).toString()));
        dv.setMonto(Float.valueOf(jTable2.getValueAt(i, 3).toString()));
        ldv.add(dv);
        }
        fiado.setDetalle(ldv);
        
          //Modifico el Almacen
          for(int i=0; i< jTable2.getRowCount(); i++ ){
          
            try {
                Almacen almacen= new Almacen();
                //List<Almacen> la=new FacadeAlmacen().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
                  List<Almacen> la=new FacadeAlmacen().buscarxid(Long.parseLong(jTable2.getValueAt(i, 0).toString()));
                almacen=la.get(0);
                float cantalmacen=Float.parseFloat(la.get(0).getCantidad());
                float cantvendida=Float.parseFloat(jTable2.getValueAt(i, 4).toString());
                almacen.setProducto(la.get(0).getProducto());
                almacen.setCantidad(String.valueOf(cantalmacen-cantvendida));
                almacen.setAlerta(la.get(0).getAlerta());
                almacen.setLocalizacion(la.get(0).getLocalizacion());
                AlmacenJpaController ajp=new AlmacenJpaController(emf);
                ajp.edit(almacen);
                //Actualizo la unidades en la localizacion primera
                        List<Localizacion> lista=new FacadeLocalizacion().buscarxAlmacen(String.valueOf(la.get(0).getId()),String.valueOf(la.get(0).getProducto().getId()));
                        Localizacion loca=lista.get(0);
                        System.out.println(loca.getDescripcion());
                        float cantidad=loca.getCantidad();
                        float cantcompra=Integer.parseInt(jTable2.getValueAt(i, 4).toString());
                        loca.setCantidad(cantidad-cantcompra);
                        LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                        ljc.edit(loca);
                
            } catch (Exception ex) {
                Logger.getLogger(jfFiado.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
          //Crear Cuenta fiado
            CuentaFiado cuenta=new CuentaFiado();
            cuenta.setAnticipo(Float.parseFloat(jTextField11.getText()));
            cuenta.setTotal(Float.parseFloat(jTextField10.getText()));
            Float sald=Float.parseFloat(jTextField10.getText())-Float.parseFloat(jTextField11.getText());
            cuenta.setSaldo(sald);
            fiado.setCuenta(cuenta);
            
            FiadoJpaController fjc=new FiadoJpaController(emf);
            fjc.create(fiado);
            JOptionPane.showMessageDialog(rootPane, "La operacion se realizo con Exito");
            jButton6.setEnabled(false);
        }
               if(Menu.opcion==2){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                fiado.setAnulado("SI");
                          //Modifico el Almacen
          for(int i=0; i< jTable2.getRowCount(); i++ ){
          
            
                Almacen almacen= new Almacen();
               // List<Almacen> la=new FacadeAlmacen().buscarxnombre(String.valueOf(jTable2.getValueAt(i, 1)).toUpperCase());
                  List<Almacen> la=new FacadeAlmacen().buscarxid(Long.parseLong(jTable2.getValueAt(i, 0).toString()));
                almacen=la.get(0);
                float cantalmacen=Float.parseFloat(la.get(0).getCantidad());
                float cantrepo=Float.parseFloat(jTable2.getValueAt(i, 4).toString());
                almacen.setProducto(la.get(0).getProducto());
                almacen.setCantidad(String.valueOf(cantalmacen+cantrepo));
                almacen.setAlerta(la.get(0).getAlerta());
                almacen.setLocalizacion(la.get(0).getLocalizacion());
                AlmacenJpaController ajp=new AlmacenJpaController(emf);
                ajp.edit(almacen);
                //Actualizo la unidades en la localizacion primera
                        List<Localizacion> lista=new FacadeLocalizacion().buscarxAlmacen(String.valueOf(la.get(0).getId()),String.valueOf(la.get(0).getProducto().getId()));
                        Localizacion loca=lista.get(0);
                        System.out.println(loca.getDescripcion());
                        float cantidad=loca.getCantidad();
                        float cantcompra=Integer.parseInt(jTable2.getValueAt(i, 4).toString());
                        loca.setCantidad(cantidad+cantcompra);
                        LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                        ljc.edit(loca);
                
          }
                
                FiadoJpaController cjc=new FiadoJpaController(emf);
                cjc.edit(fiado);
                JOptionPane.showMessageDialog(rootPane, "La operacion se realizo con Exito");
                jButton6.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(jfContrato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        // TODO add your handling code here:
         float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField11KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfFiado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfFiado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfFiado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfFiado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfFiado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponenetes() {
    if(Menu.opcion==1){    
    jTextField1.setEnabled(true);
    jTextField2.setEnabled(true);
    jTextField3.setEnabled(true);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(true);
    jTextField10.setEnabled(true);
    jTextField11.setEnabled(true);
    jTextField11.setText("0");
    jTextField12.setEnabled(false);
    jTextField12.setText("0");
    jXDatePicker1.setEnabled(false);
    jXDatePicker1.setFormats("dd/MM/yyyy");
    Date hoy=new Date();
    jXDatePicker1.setDate(hoy);
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);
    jButton5.setEnabled(true);
    jButton6.setEnabled(true);
    jButton7.setEnabled(true);
    jButton8.setEnabled(true);
    cargarTablaProducto();
    inicializarTabla2();
    inicializatTablaproducto();
    }
    if(Menu.opcion==2){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField12.setText("0"); 
   //jTextField11.setText("0");
    jXDatePicker1.setEnabled(false);
    jXDatePicker1.setFormats("dd/MM/yyyy");
   // Date hoy=new Date();
    //jXDatePicker1.setDate(hoy);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(true);
    jButton7.setEnabled(true);
    jButton8.setEnabled(true);
    jdBuscarFiado ventana=new  jdBuscarFiado(this, true);
    ventana.setVisible(true);
    fiado=ventana.fiado;
    //Cargar Datos   
    inicializarTabla2();
    inicializatTablaproducto();
    CargarDatosFiado();
    }
      if(Menu.opcion==4){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField12.setText("0");
    //jTextField11.setText("0");
    jXDatePicker1.setEnabled(false);
    jXDatePicker1.setFormats("dd/MM/yyyy");
   // Date hoy=new Date();
    //jXDatePicker1.setDate(hoy);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(false);
    jButton7.setEnabled(true);
    jButton8.setEnabled(true);
    jdBuscarFiado ventana=new  jdBuscarFiado(this, true);
    ventana.setVisible(true);
    fiado=ventana.fiado;
    //Cargar Datos
    inicializarTabla2();
    inicializatTablaproducto();
    CargarDatosFiado();
    }
    
    }
      public void cargarTablaProducto(){
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().listar();
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
       // modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
        //vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    }
       public void inicializarTabla2(){
       modelo2.addColumn("Id");
       modelo2.addColumn("Producto");
       modelo2.addColumn("Proveedor");
       modelo2.addColumn("Precio");
       modelo2.addColumn("Cantidad");
       jTable2.setModel(modelo2);
    }
         private void buscarProducto() {
       EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().buscarxnombre(jTextField2.getText().toUpperCase());
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        //modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
       // vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    }
        private void buscarxcodigo() {
       EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().buscarxcod(jTextField8.getText());
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        //modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
        //vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    }
    public void limpiarCampos(){
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    }
    private void calcularTotal() {
    float total=0;    
    for(int i=0; i<jTable2.getRowCount();i++){
    float precio= Float.parseFloat(jTable2.getValueAt(i, 3).toString());
    float cantidad=Float.parseFloat(jTable2.getValueAt(i, 4).toString());
    float calculo= precio*cantidad;
    total=total+calculo;
    }
    jTextField10.setText(String.valueOf(total));
    }

    private void CargarDatosFiado() {
      jTextField1.setText(fiado.getNombrefiador().toUpperCase());
      jXDatePicker1.setDate(fiado.getFecha());
      //Cargar Tabla Productos
       modelo2=new DefaultTableModel();
       modelo2.addColumn("Id");
       modelo2.addColumn("Producto");
       modelo2.addColumn("Proveedor");
       modelo2.addColumn("Precio");
       modelo2.addColumn("Cantidad");
       List<detalleFiado> listadetalle=fiado.getDetalle();
       for(int j=0; j<listadetalle.size(); j++){
      Vector vector = new Vector();
      vector.add(listadetalle.get(j).getId());
      vector.add(listadetalle.get(j).getProducto().getDescripcion());
      vector.add(listadetalle.get(j).getProducto().getProveedor().getNombre());
      vector.add(listadetalle.get(j).getMonto());
      vector.add(listadetalle.get(j).getCantidad());
      
      modelo2.addRow(vector);
       }
       jTable2.setModel(modelo2);
       jTextField10.setText(String.valueOf(fiado.getMonto()));
       jTextField11.setText(String.valueOf(fiado.getAnticipo()));
       jTextField12.setText(String.valueOf(fiado.getSaldo()));
    }

    private void inicializatTablaproducto() {
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        jTable1.setModel(modeloTabla);
    }
}
