/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.ComprasJpaController;
import Controladores.ComprasinStockJpaController;
import Controladores.DetalleCuentaProvedorSinStockJpaController;
import Entidades.ComprasinStock;
import Entidades.Deposito;
import Entidades.DetalleCuentaProvedorSinStock;
import Entidades.PagoCompraSinStock;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo
 */
public class JfPagoCompraSinStock extends javax.swing.JFrame {
    ComprasinStock compra;
    DetalleCuentaProvedorSinStock dc;
    /**
     * Creates new form PagoCompraSinStock
     */
    public JfPagoCompraSinStock() {
        initComponents();
        inicializarComponentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jTextField1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel2.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jTextField2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel3.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jTextField3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel4.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jTextField4.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel6.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel7.text")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CONTADO", "DEPOSITO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel9.text")); // NOI18N

        jTextField5.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jTextField5.text")); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel10.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jLabel10.text")); // NOI18N

        jTextField6.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jTextField6.text")); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(JfPagoCompraSinStock.class, "JfPagoCompraSinStock.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6)
                            .addComponent(jComboBox1, 0, 262, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BuscarComprasSinStock ventana=new BuscarComprasSinStock(this, true);
        ventana.setVisible(true);
        compra=ventana.compra;
        CargarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("CONTADO")){
        jTextField6.setEnabled(false);
        }else{
        jTextField6.setEnabled(true);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float monto=Float.parseFloat(jTextField3.getText());
        float saldo=Float.parseFloat(jTextField4.getText());
        if(monto > saldo){
        if(!jTextField5.getText().equals("")&& jXDatePicker1.getDate()!=null && jComboBox1.getSelectedItem().toString().equals("CONTADO")){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                PagoCompraSinStock pago=new PagoCompraSinStock();
                pago.setFecha(jXDatePicker1.getDate());
                pago.setMonto(Float.parseFloat(jTextField5.getText()));
                List<DetalleCuentaProvedorSinStock> listadetallecuenta=new ArrayList<>();
                listadetallecuenta=compra.getCuenta().getDetalle();
                DetalleCuentaProvedorSinStock detalle=new DetalleCuentaProvedorSinStock();
                detalle.setFecha(jXDatePicker1.getDate());
                detalle.setMonto(Float.parseFloat(jTextField5.getText()));
                detalle.setPago(pago);
                detalle.setTipo(jComboBox1.getSelectedItem().toString());
                detalle.setAnulado("NO");
                detalle.setUsu(JLogin.usu);
                listadetallecuenta.add(detalle);
                compra.getCuenta().setDetalle(listadetallecuenta);
                //modificar Saldo y estado de la cuenta si es necesario
                float saldooriginal=compra.getCuenta().getSaldo();
                float saldo1=Float.parseFloat(jTextField5.getText())+saldooriginal;
                if(saldo1 >= compra.getPrecio_totol()){
                compra.getCuenta().setSaldo(compra.getPrecio_totol());
                compra.getCuenta().setEstado("CERRADO");
                }
                if(saldo1 < compra.getPrecio_totol()){
                compra.getCuenta().setSaldo(saldo1);
                //compra.getCuenta().setEstado("CERRADO");
                }
                ComprasinStockJpaController cjc=new ComprasinStockJpaController(emf);
                cjc.edit(compra);
                JOptionPane.showMessageDialog(rootPane, "La operacion se Realizo con Exito");
                CargarDatos();
            } catch (Exception ex) {
                Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(Level.SEVERE, null, ex);
            }       
        }
             if(!jTextField5.getText().equals("")&& jXDatePicker1.getDate()!=null && jComboBox1.getSelectedItem().toString().equals("DEPOSITO")){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                Deposito pago=new Deposito();
                pago.setFecha(jXDatePicker1.getDate());
                pago.setMonto(Float.parseFloat(jTextField5.getText()));
                pago.setNro_cuenta(jTextField6.getText());
                List<DetalleCuentaProvedorSinStock> listadetallecuenta=new ArrayList<>();
                listadetallecuenta=compra.getCuenta().getDetalle();
                DetalleCuentaProvedorSinStock detalle=new DetalleCuentaProvedorSinStock();
                detalle.setFecha(jXDatePicker1.getDate());
                detalle.setMonto(Float.parseFloat(jTextField5.getText()));
                detalle.setDeposito(pago);
                detalle.setTipo(jComboBox1.getSelectedItem().toString());
                detalle.setAnulado("NO");
                detalle.setUsu(JLogin.usu);
                listadetallecuenta.add(detalle);
                compra.getCuenta().setDetalle(listadetallecuenta);
                float saldooriginal=compra.getCuenta().getSaldo();
                float saldo1=Float.parseFloat(jTextField5.getText())+saldooriginal;
                if(saldo1 >= compra.getPrecio_totol()){
                compra.getCuenta().setSaldo(compra.getPrecio_totol());
                compra.getCuenta().setEstado("CERRADO");
                }
                if(saldo1 < compra.getPrecio_totol()){
                compra.getCuenta().setSaldo(saldo1);
                //compra.getCuenta().setEstado("CERRADO");
                }
                ComprasinStockJpaController cjc=new ComprasinStockJpaController(emf);
                cjc.edit(compra);
                JOptionPane.showMessageDialog(rootPane, "La operacion se Realizo con Exito");
                CargarDatos();
            } catch (Exception ex) {
                Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         }
        }else{JOptionPane.showMessageDialog(rootPane,"Cuenta saldada");}
        if(Menu.opcion==11){
        if(dc!=null){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                dc.setAnulado("SI");
                float sal=Float.parseFloat(jTextField4.getText());
                float pd=Float.parseFloat(jTextField5.getText());
                compra.getCuenta().setSaldo(sal+pd);
                compra.getCuenta().setEstado("A SALDAR");
                DetalleCuentaProvedorSinStockJpaController djc=new DetalleCuentaProvedorSinStockJpaController(emf);
                djc.edit(dc);
                
                ComprasinStockJpaController cjc=new ComprasinStockJpaController(emf);
                cjc.edit(compra);
            } catch (Exception ex) {
                Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
          if (jTable2.getSelectedRow() != -1 && Menu.opcion==11) {
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable2.getValueAt(jTable2.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      dc= new DetalleCuentaProvedorSinStockJpaController(emf).findDetalleCuentaProvedorSinStock(valor);
          JOptionPane.showMessageDialog(rootPane, "Selecciono el pago:"+ dc.getId() +"");
      jComboBox1.setSelectedItem(dc.getTipo());
      jXDatePicker1.setDate(dc.getFecha());
      jTextField5.setText(String.valueOf(dc.getMonto()));
      if(dc.getDeposito()!=null){
      jTextField6.setText(String.valueOf(dc.getDeposito().getNro_cuenta()));
      }
      }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPagoCompraSinStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPagoCompraSinStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
    if(Menu.opcion==10){    
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(true);
    jTextField6.setEnabled(false);
    jXDatePicker1.setEnabled(true);
    jXDatePicker1.setFormats("dd/MM/yyyy");
    Date hoy =new Date();
    jXDatePicker1.setDate(hoy);
    inicializarTablaComprase();
    inicializarTabla2();
     }
    if(Menu.opcion==11){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jButton2.setText("Anular");
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jXDatePicker1.setEnabled(false);
    jXDatePicker1.setFormats("dd/MM/yyyy");
    Date hoy =new Date();
    jXDatePicker1.setDate(hoy);
    jComboBox1.setEnabled(false);
    inicializarTablaComprase();
    inicializarTabla2();
    }
    }

    private void CargarDatos() {
     DefaultTableModel modeloTabla=new DefaultTableModel();    
       modeloTabla.addColumn("Producto");
       modeloTabla.addColumn("Precio de compra");
       modeloTabla.addColumn("Cantidad");
     jTextField1.setText(String.valueOf(compra.getId()));
     jTextField2.setText(compra.getProveedor().getNombre());
     jTextField3.setText(String.valueOf(compra.getPrecio_totol()));
     jTextField4.setText(String.valueOf(compra.getCuenta().getSaldo()));
     for(int i=0; i<compra.getDetallecompra().size();i++){
     Vector vector=new Vector();
     vector.add(compra.getDetallecompra().get(i).getProducto());
     vector.add(compra.getDetallecompra().get(i).getPrecio());
     vector.add(compra.getDetallecompra().get(i).getCantidad());
     modeloTabla.addRow(vector);
     }
     jTable1.setModel(modeloTabla);
       SimpleDateFormat formato=new SimpleDateFormat("dd-MM-yyyy");
   
      DefaultTableModel modeloTabla1=new DefaultTableModel();
        modeloTabla1.addColumn("Id");
        modeloTabla1.addColumn("Fecha");
        modeloTabla1.addColumn("Proveedor");
        modeloTabla1.addColumn("Monto");
        modeloTabla1.addColumn("Saldo");
        modeloTabla1.addColumn("Estado");
     for(int j=0; j<compra.getCuenta().getDetalle().size();j++){
     if(compra.getCuenta().getDetalle().get(j).getAnulado().equals("NO")){    
     Vector vector=new Vector();
     vector.add(compra.getCuenta().getDetalle().get(j).getId());
     String MyFecha = formato.format(compra.getCuenta().getDetalle().get(j).getFecha());
        vector.add(MyFecha);
     vector.add(compra.getProveedor().getNombre());
     vector.add(compra.getCuenta().getDetalle().get(j).getMonto());
     vector.add(compra.getCuenta().getSaldo());
     vector.add(compra.getCuenta().getEstado());
     modeloTabla1.addRow(vector);
     }
     }
     jTable2.setModel(modeloTabla1);
     }
    

    private void inicializarTablaComprase() {
   DefaultTableModel modeloTabla=new DefaultTableModel();
       modeloTabla.addColumn("Id");
       modeloTabla.addColumn("Producto");
       modeloTabla.addColumn("Proveedor");
       modeloTabla.addColumn("Precio de compra");
       modeloTabla.addColumn("Cantidad");
    jTable1.setModel(modeloTabla);
    
    }

    private void inicializarTabla2() {
    DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Monto");
        modeloTabla.addColumn("Saldo");
        modeloTabla.addColumn("Estado");
     jTable2.setModel(modeloTabla);
    
    }
}
