/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.AlumnoJpaController;
import Controladores.ContratoJpaController;
import Controladores.cuenta_contratoJpaController;
import Controladores.detalle_cuenta_contratoJpaController;
import Entidades.Alumno;
import Entidades.Contrato;
import Entidades.Detalle_Contrato;
import Entidades.Tipo_Doc;
import Entidades.cuenta_contrato;
import Entidades.detalle_cuenta_contrato;
import Facade.FacadeAlumno;
import Facade.FacadeContrato;
import Facade.FacadeTipoDoc;
import static Vistas.ConsultarContrato.contrato;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo
 */
public class jfPago_cuenta_contrato extends javax.swing.JFrame {
    Contrato contrato;
    Alumno alumno;
    detalle_cuenta_contrato dcc;
    float contadorpago=0; 
    /**
     * Creates new form jfPago_cuenta_contrato
     */
    public jfPago_cuenta_contrato() {
        initComponents();
        inicializarComponentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel2.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField1.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel3.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField2.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel11.text")); // NOI18N

        jTextField8.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField8.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel12.text")); // NOI18N

        jTextField9.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField9.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel13.text")); // NOI18N

        jTextField10.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField10.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel5.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField3.text")); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar2.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel6.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField4.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel7.text")); // NOI18N

        jTextField5.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField5.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel8.text")); // NOI18N

        jTextField6.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField6.text")); // NOI18N

        jLabel16.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel16.text")); // NOI18N

        jTextField11.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField11.text")); // NOI18N

        jLabel17.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel17.text")); // NOI18N

        jTextField12.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField12.text")); // NOI18N

        jLabel18.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel18.text")); // NOI18N

        jTextField13.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField13.text")); // NOI18N

        jButton5.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel19.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel19.text")); // NOI18N

        jTextField14.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField14.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel14.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel14.text")); // NOI18N

        jLabel20.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel20.text")); // NOI18N

        jTextField15.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField15.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel9.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel10.text")); // NOI18N

        jTextField7.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jTextField7.text")); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText(org.openide.util.NbBundle.getMessage(jfPago_cuenta_contrato.class, "jfPago_cuenta_contrato.jLabel15.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsultarContrato ventana=new ConsultarContrato(null, true);
        ventana.setVisible(true);
        contrato=ventana.cont;
        // cantidad de integrantes
        jTextField14.setText(String.valueOf(contrato.getAlumnos().size()));
        System.out.println(contrato.getOrganizacion().getNombre());
        //if(contrato!=null){
        jTextField1.setText(contrato.getNroContrato());
        jTextField2.setText(contrato.getOrganizacion().getNombre());
        jTextField8.setText(String.valueOf(contrato.getTotal()));
        jTextField9.setText(String.valueOf(contrato.getCuenta_contrato().getAnticipo()));
        jTextField10.setText(String.valueOf(contrato.getCuenta_contrato().getSaldo()));
        llenarTablaIntegrantes();
        llenarTablaPagos();
        //}
        if(contrato.getEstado().equals("CERRADO")){
        jLabel15.setText("CONTRATO SALDADO");
        jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!jTextField3.getText().equals("") && !jTextField1.getText().equals("")){
        buscarUnIntegrante();
        }
        if(!jTextField3.getText().equals("") && jTextField1.getText().equals("")){
        buscarIntegranteEnContrato();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      if(jTable1.getSelectedRow()!=-1){
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      alumno=new AlumnoJpaController(emf).findAlumno(valor);
      jTextField4.setText(alumno.getApellido()+" "+ alumno.getNombre());
      jTextField5.setText(alumno.getTipodoc());
      jTextField6.setText(alumno.getDni());
      llenarTablaPagoAlumno();
      }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Menu.opcion==1){
        if(contrato!=null && alumno!=null && jXDatePicker1.getDate()!=null && !jTextField7.getText().equals("")){
            if(contrato.getEstado().equals("EN TRAMITE")){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                detalle_cuenta_contrato dcc=new detalle_cuenta_contrato();
                dcc.setAlumno(alumno);
                dcc.setFecha(jXDatePicker1.getDate());
                dcc.setMonto_pago(Float.parseFloat(jTextField7.getText()));
                dcc.setAnulado("NO");
                dcc.setUsu(JLogin.usu);
                float saldo=Float.parseFloat(jTextField10.getText())-Float.parseFloat(jTextField7.getText());
                ContratoJpaController cjc=new ContratoJpaController(emf);
                List<detalle_cuenta_contrato> listadetalle=contrato.getCuenta_contrato().getListadetallecuenta();
                listadetalle.add(dcc);
                cuenta_contrato cuenta=contrato.getCuenta_contrato();
                cuenta.setListadetallecuenta(listadetalle);
                cuenta.setSaldo(saldo);
                if(saldo <=0){
                contrato.setEstado("SALDADO");
                }
                contrato.setCuenta_contrato(cuenta);
                cjc.edit(contrato);
                JOptionPane.showMessageDialog(rootPane, "Pago registrado");
                limpiarCampos();
                //Refresca la vista
                jTextField1.setText(contrato.getNroContrato());
        jTextField2.setText(contrato.getOrganizacion().getNombre());
        jTextField8.setText(String.valueOf(contrato.getTotal()));
        jTextField9.setText(String.valueOf(contrato.getCuenta_contrato().getAnticipo()));
        jTextField10.setText(String.valueOf(contrato.getCuenta_contrato().getSaldo()));
        llenarTablaIntegrantes();
        llenarTablaPagos();
        //}
        if(contrato.getEstado().equals("CERRADO")){
        jLabel15.setText("CONTRATO SALDADO");
        jButton3.setEnabled(false);
        }
                
            } catch (Exception ex) {
                Logger.getLogger(jfPago_cuenta_contrato.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{JOptionPane.showMessageDialog(rootPane, "No se puede realizar la Operacion, Contrato Saldado");}
            
        }else{JOptionPane.showMessageDialog(rootPane, "Datos Imcompletos");} 
       }
        if(Menu.opcion==2){
        if(dcc!=null){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                dcc.setAnulado("SI");
                detalle_cuenta_contratoJpaController dccjc=new detalle_cuenta_contratoJpaController(emf);
                dccjc.edit(dcc);
                cuenta_contrato cuenta=contrato.getCuenta_contrato();
                float saldo=Float.parseFloat(jTextField10.getText())+Float.parseFloat(jTextField7.getText());
                cuenta.setSaldo(saldo);
                cuenta_contratoJpaController cjc=new cuenta_contratoJpaController(emf);
                cjc.edit(cuenta);
                if(saldo>0){
                contrato.setEstado("EN TRAMITE");
                }else{
                contrato.setEstado("SALDADO");
                }
                ContratoJpaController cojc=new ContratoJpaController(emf);
                cojc.edit(contrato);
            } catch (Exception ex) {
                Logger.getLogger(jfPago_cuenta_contrato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
      if(jTable2.getSelectedRow()!=-1 && Menu.opcion==2){
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable2.getValueAt(jTable2.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      dcc=new detalle_cuenta_contratoJpaController(emf).finddetalle_cuenta_contrato(valor);
      jXDatePicker1.setDate(dcc.getFecha());
      jTextField7.setText(String.valueOf(dcc.getMonto_pago()));
      }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(contrato!=null){
        jTextField1.setText(contrato.getNroContrato());
        jTextField2.setText(contrato.getOrganizacion().getNombre());
        jTextField8.setText(String.valueOf(contrato.getTotal()));
        jTextField9.setText(String.valueOf(contrato.getCuenta_contrato().getAnticipo()));
        jTextField10.setText(String.valueOf(contrato.getCuenta_contrato().getSaldo()));
        llenarTablaIntegrantes();
        llenarTablaPagos();
        //}
        if(contrato.getEstado().equals("CERRADO")){
        jLabel15.setText("CONTRATO SALDADO");
        jButton3.setEnabled(false);
        }
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPago_cuenta_contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPago_cuenta_contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPago_cuenta_contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPago_cuenta_contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPago_cuenta_contrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
    if(Menu.opcion==1){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(true);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(true);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
     jTextField14.setEnabled(false);
    jTextField15.setEnabled(false);
    Date hoy=new Date();
    jXDatePicker1.setFormats("dd/MM/yyyy");
    jXDatePicker1.setDate(hoy);
    inicializarTablaContrato();
    inicializarcombo();
    inicializarTablaPago();
    }
    if(Menu.opcion==2){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
     jTextField14.setEnabled(false);
    jTextField15.setEnabled(false);
    Date hoy=new Date();
    jXDatePicker1.setFormats("dd/MM/yyyy");
    jXDatePicker1.setDate(hoy);
    inicializarTablaContrato();
    inicializarcombo();
    inicializarTablaPago();
    jButton3.setText("Anular Pago");
    }
  if(Menu.opcion==4){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
     jTextField14.setEnabled(false);
    jTextField15.setEnabled(false);
    Date hoy=new Date();
    jXDatePicker1.setFormats("dd/MM/yyyy");
    jXDatePicker1.setDate(hoy);
    inicializarTablaContrato();
    inicializarcombo();
    inicializarTablaPago();
    jButton3.setText("Consulta Pago");
    }
  
    
    }

    private void inicializarTablaContrato() {
      DefaultTableModel modeloTabla = new DefaultTableModel(); 
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Nro de contrato");
    modeloTabla.addColumn("Fecha inicio");
    modeloTabla.addColumn("Fecha Fin");
    modeloTabla.addColumn("Organizacion");
    modeloTabla.addColumn("Año");
    modeloTabla.addColumn("Division");
    modeloTabla.addColumn("Estado");
    
    jTable1.setModel(modeloTabla);
    }

    private void inicializarTablaPago() {
    DefaultTableModel modeloTabla = new DefaultTableModel(); 
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Integrante");
    modeloTabla.addColumn("Fecha Entrega");
    modeloTabla.addColumn("Monto Entrega");
    
    jTable2.setModel(modeloTabla);
    }

    private void inicializarcombo() {
         DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
     List<Tipo_Doc> lista;
     lista=new FacadeTipoDoc().listar();
     if(lista.get(0).getId()!=null){
      for(int i=0;  i < lista.size(); i++){
      Vector vector = new Vector();
      vector.add(lista.get(i).getDescripcion());
      modeloCombo.addElement(lista.get(i).getDescripcion());
     }
     jComboBox1.setModel(modeloCombo);            
     }
    }

    private void llenarTablaPagos() {
    SimpleDateFormat formato=new SimpleDateFormat("dd-MM-yyyy");
    List<detalle_cuenta_contrato> lista=new ArrayList<>();
    lista=contrato.getCuenta_contrato().getListadetallecuenta();
    DefaultTableModel modeloTabla = new DefaultTableModel(); 
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Integrante");
    modeloTabla.addColumn("Fecha Entrega");
    modeloTabla.addColumn("Monto Entrega");
    float contadorpag=0;   
    
    
    
    for (int i = 0; i < lista.size(); i++) {
      if(lista.get(i).getAnulado().equals("NO")){  
      Vector vector = new Vector();
      vector.add(lista.get(i).getId());
      vector.add(lista.get(i).getAlumno().getApellido()+" "+lista.get(i).getAlumno().getNombre());
      String MyFecha = formato.format(lista.get(i).getFecha());
      vector.add(MyFecha);
      vector.add(lista.get(i).getMonto_pago());
      contadorpag=contadorpag+lista.get(i).getMonto_pago();
      
      modeloTabla.addRow(vector);
      }
    }
     jTable2.setModel(modeloTabla); 
     jTextField15.setText(String.valueOf(contadorpag));
    }

    private void llenarTablaIntegrantes() {
        List<Alumno> lista;
        lista=contrato.getAlumnos();
         DefaultTableModel modeloTabla = new DefaultTableModel(); 
      
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Organizacion");
    modeloTabla.addColumn("Promocion");
    modeloTabla.addColumn("Apellido");
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Tipo doc");
    modeloTabla.addColumn("Nro doc");
    modeloTabla.addColumn("Telefono");
    modeloTabla.addColumn("Email");
    modeloTabla.addColumn("Domicilio");
    
    
    
    for (int i = 0; i < lista.size(); i++) {
      Vector vector = new Vector();
      vector.add(lista.get(i).getId());
      vector.add(lista.get(i).getOrg().getNombre()+"-"+lista.get(i).getOrg().getAnio()+" "+lista.get(i).getOrg().getDivision());
      vector.add(lista.get(i).getPromocion());
      vector.add(lista.get(i).getApellido());
      vector.add(lista.get(i).getNombre());
      vector.add(lista.get(i).getTipodoc());
      vector.add(lista.get(i).getDni());
      vector.add(lista.get(i).getTel());
      vector.add(lista.get(i).getEmail());
      vector.add(lista.get(i).getDomicilio());
      
      modeloTabla.addRow(vector);
    }
     jTable1.setModel(modeloTabla);
     
    }

    private void buscarUnIntegrante() {
     List<Alumno> lista;
       lista=contrato.getAlumnos();
       DefaultTableModel modeloTabla = new DefaultTableModel(); 
      
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Organizacion");
    modeloTabla.addColumn("Promocion");
    modeloTabla.addColumn("Apellido");
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Tipo doc");
    modeloTabla.addColumn("Nro doc");
    modeloTabla.addColumn("Telefono");
    modeloTabla.addColumn("Email");
    modeloTabla.addColumn("Domicilio");
    
    
    
    for (int i = 0; i < lista.size(); i++) {
      if(lista.get(i).getDni().equals(jTextField3.getText())){
      Vector vector = new Vector();
      vector.add(lista.get(i).getId());
      vector.add(lista.get(i).getOrg().getNombre()+"-"+lista.get(i).getOrg().getAnio()+" "+lista.get(i).getOrg().getDivision());
      vector.add(lista.get(i).getPromocion());
      vector.add(lista.get(i).getApellido());
      vector.add(lista.get(i).getNombre());
      vector.add(lista.get(i).getTipodoc());
      vector.add(lista.get(i).getDni());
      vector.add(lista.get(i).getTel());
      vector.add(lista.get(i).getEmail());
      vector.add(lista.get(i).getDomicilio());
      
      modeloTabla.addRow(vector);
      }  
      
    }
     jTable2.setModel(modeloTabla);
     
    }

    private void llenarTablaPagoAlumno() {
     contadorpago=0;  
     SimpleDateFormat formato=new SimpleDateFormat("dd-MM-yyyy");
     List<detalle_cuenta_contrato> lista=new ArrayList<>();
    lista=contrato.getCuenta_contrato().getListadetallecuenta();
    DefaultTableModel modeloTabla = new DefaultTableModel(); 
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Integrante");
    modeloTabla.addColumn("Fecha Entrega");
    modeloTabla.addColumn("Monto Entrega");
       
    
    
    
    for (int i = 0; i < lista.size(); i++) {
      if(alumno.getId()==lista.get(i).getAlumno().getId()){
      if(lista.get(i).getAnulado().equals("NO")){
      System.out.println("Entro en llenar tabla pago");
      Vector vector = new Vector();
      vector.add(lista.get(i).getId());
      vector.add(lista.get(i).getAlumno().getApellido()+" "+lista.get(i).getAlumno().getNombre());
      String MyFecha = formato.format(lista.get(i).getFecha());
      vector.add(MyFecha);
      vector.add(lista.get(i).getMonto_pago());
      contadorpago=contadorpago+lista.get(i).getMonto_pago();
      
      modeloTabla.addRow(vector);
          }
      }  
       }
     jTable2.setModel(modeloTabla);
     jTextField15.setText(String.valueOf(contadorpago));
     jTextField11.setText(String.valueOf(contadorpago));
     jTextField13.setText(String.valueOf(contrato.getCuenta_contrato().getSaldoIntegrante()));
     float deuda=contrato.getCuenta_contrato().getSaldoIntegrante()-contadorpago;
     jTextField12.setText(String.valueOf(deuda));
    
    }

    private void limpiarCampos() {
    jTextField1.setText("");
    jTextField2.setText("");
     jTextField3.setText("");
    jTextField4.setText("");
     jTextField5.setText("");
    jTextField6.setText("");
     jTextField7.setText("");
    jTextField8.setText("");
     jTextField9.setText("");
    jTextField10.setText("");
    jTextField11.setText("");
    jTextField12.setText("");
    jTextField13.setText("");
    inicializarComponentes();
    }

    private void buscarIntegranteEnContrato() {
       List<Contrato> listacontrato=new FacadeContrato().listar();
       List<Alumno> lista;
       DefaultTableModel modeloTabla = new DefaultTableModel(); 
      
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Organizacion");
    modeloTabla.addColumn("Promocion");
    modeloTabla.addColumn("Apellido");
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Tipo doc");
    modeloTabla.addColumn("Nro doc");
    modeloTabla.addColumn("Telefono");
    modeloTabla.addColumn("Email");
    modeloTabla.addColumn("Domicilio");
    
  for(int j=0; j<listacontrato.size(); j++){
  lista=listacontrato.get(j).getAlumnos();
  for(int z=0; z < lista.size();z++){
  if(lista.get(z).getDni().equals(jTextField3.getText())){
  contrato=listacontrato.get(j);
  z=lista.size();
  j=listacontrato.size();
    }
   }
  } 
   if(contrato!=null){
   lista=contrato.getAlumnos();
   for (int i = 0; i < lista.size(); i++) {
      if(lista.get(i).getDni().equals(jTextField3.getText())){
      Vector vector = new Vector();
      vector.add(lista.get(i).getId());
      vector.add(lista.get(i).getOrg().getNombre()+"-"+lista.get(i).getOrg().getAnio()+" "+lista.get(i).getOrg().getDivision());
      vector.add(lista.get(i).getPromocion());
      vector.add(lista.get(i).getApellido());
      vector.add(lista.get(i).getNombre());
      vector.add(lista.get(i).getTipodoc());
      vector.add(lista.get(i).getDni());
      vector.add(lista.get(i).getTel());
      vector.add(lista.get(i).getEmail());
      vector.add(lista.get(i).getDomicilio());
      
      modeloTabla.addRow(vector);
      }
   }  
      
    }
     jTable2.setModel(modeloTabla);
     
     if(contrato!=null){
    System.out.println(contrato.getOrganizacion().getNombre());
        //if(contrato!=null){
        jTextField1.setText(contrato.getNroContrato());
        jTextField2.setText(contrato.getOrganizacion().getNombre());
        jTextField8.setText(String.valueOf(contrato.getTotal()));
        jTextField9.setText(String.valueOf(contrato.getCuenta_contrato().getAnticipo()));
        jTextField10.setText(String.valueOf(contrato.getCuenta_contrato().getSaldo()));
        llenarTablaIntegrantes();
        llenarTablaPagos();
        //}
        if(contrato.getEstado().equals("CERRADO")){
        jLabel15.setText("CONTRATO SALDADO");
        jButton3.setEnabled(false);
        }
   }
    }
}
