/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.AlmacenJpaController;
import Controladores.CodigoBarraJpaController;
import Controladores.LocalizacionJpaController;
import Controladores.PrecioJpaController;
import Controladores.ProductoJpaController;
import Controladores.TarjetaJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Almacen;
import Entidades.CodigoBarra;
import Entidades.Localizacion;
import Entidades.Precio;
import Entidades.Producto;
import Entidades.Proveedor;
import Entidades.Tarjeta;
import Entidades.TipoUnidades;
import Entidades.Tipo_Doc;
import Facade.FacadeAlmacen;
import Facade.FacadeLocalizacion;
import Facade.FacadeProducto;
import Facade.FacadeProveedor;
import Facade.FacadeTarjeta;
import Facade.FacadeTipoDoc;
import Facade.FacadeTipoUnidades;
import Reportes.Reporte;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author laura
 */
public class JfProducto extends javax.swing.JFrame {
    int menu=Menu.opcion;
    Producto prod;
    int codigoministerial=0;// bandera para saber si se cargo un codigo ministerial
    String cod;
    int num;
    long idprod;

    /**
     * Creates new form JfProducto
     */
    public JfProducto() {
        initComponents();
         setLocationRelativeTo(null);
        inicializarComponentes();
        deshabilitarpizzeria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setText("*Proveedor:");

        jLabel7.setText("*Producto:");

        jLabel1.setText("Ingrese los datos:");

        jLabel13.setText("*Codigo:");

        jLabel14.setText("Tipo de Unidad:");

        jButton1.setText("Generar Codigo de Barra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Talle:");

        jCheckBox1.setText("De Taller");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("Precios:");

        jLabel4.setText("*Precio Compra: $");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel5.setText("*Precio Venta: $");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setText("Almacen:");

        jLabel9.setText("*Cantidad:");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel10.setText("*Alerta:");

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel11.setText("*Localizacion:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jButton4.setText("Imprimir Cod de Barra");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel12.setText("Productos cargados:");

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Producto", "Proveedor", "Precio real", "Precio Contado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(menu==1){
        List<Producto> listap=new FacadeProducto().buscarxCod(jTextField7.getText());
        int valida=listap.size();
        if(valida==0){         
        if(!jTextField1.getText().equals("")&&!jTextField2.getText().equals("")&&!jTextField3.getText().equals("")&&!jTextField4.getText().equals("")&&!jTextField5.getText().equals("")&&!jComboBox3.getSelectedItem().equals("")&&!jTextField7.getText().equals("")){    
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
        Producto prod=new Producto();
        prod.setCod(jTextField7.getText());
        prod.setDescripcion(jTextField3.getText().toUpperCase());
        List<Proveedor> prov=new FacadeProveedor().buscarxnombre(jComboBox1.getSelectedItem().toString());
        prod.setProveedor(prov.get(0));
        List<TipoUnidades> tu=new FacadeTipoUnidades().buscarxnombre(jComboBox2.getSelectedItem().toString());
        prod.setUnidad(tu.get(0));
        prod.setTalle(jTextField6.getText().toUpperCase());
        Precio precio= new Precio();
        precio.setPrecio_real(Float.parseFloat(jTextField1.getText()));
        precio.setPrecio_contado(Float.parseFloat(jTextField2.getText()));
        //precio.setProducto(prod);
        List<Tarjeta> tarjera=new FacadeTarjeta().listar();
        precio.setTarjeta(tarjera);
        prod.setPrecio(precio);
        //Se agrega para saber si un producto del taller
        if(jCheckBox1.isSelected()){
        prod.setDetaller(1);
        }
        if(!jCheckBox1.isSelected()){
        prod.setDetaller(0);
        }
        PrecioJpaController  prjc=new PrecioJpaController(emf);
            ProductoJpaController pjc=new ProductoJpaController(emf);
            prjc.create(precio);
       pjc.create(prod);
       idprod=prod.getId();
        //chequear para entrar datos al almacen
        Almacen almacen= new Almacen();
        if(!jTextField4.getText().equals("")&& !jTextField5.getText().equals("")&&!jComboBox3.getSelectedItem().equals("")){
            try {
                almacen.setCantidad(jTextField4.getText());
                almacen.setAlerta(jTextField5.getText());
                almacen.setLocalizacion(jComboBox3.getSelectedItem().toString().toUpperCase());
                almacen.setProducto(prod);
                AlmacenJpaController ajc= new AlmacenJpaController(emf);
                ajc.create(almacen);
                llenarTablaProd();
                if(jTable2.getRowCount()==1){
                //Crea la localizacion
                List<Localizacion> llocalizacion=new FacadeLocalizacion().buscarxdes(jComboBox3.getSelectedItem().toString());
                Localizacion localizacion=llocalizacion.get(0);
                localizacion.setCantidad(Integer.parseInt(jTextField4.getText()));
                localizacion.setDescripcion(jComboBox3.getSelectedItem().toString().toUpperCase());
                localizacion.setId_almacen(String.valueOf(almacen.getId()));
                localizacion.setId_producto(String.valueOf(almacen.getProducto().getId()));
                LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                ljc.edit(localizacion);
                }
                if(jTable2.getRowCount()>1){
                List<Localizacion> llocalizacion=new FacadeLocalizacion().buscarxdes(jComboBox3.getSelectedItem().toString());
                Localizacion localizacion=new Localizacion();
                localizacion.setCantidad(Float.parseFloat(jTextField4.getText()));
                localizacion.setDescripcion(jComboBox3.getSelectedItem().toString().toUpperCase());
                localizacion.setId_almacen(String.valueOf(almacen.getId()));
                localizacion.setId_producto(String.valueOf(almacen.getProducto().getId()));
                LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                ljc.create(localizacion);
                }
            } catch (Exception ex) {
                Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jButton4.setEnabled(true);
       JOptionPane.showMessageDialog(rootPane, "El registro se guardo con exito");
       limpiarCampos();
       //si se cargo un codigo ministerial agrego a la tabla codigo ministerial
       if(codigoministerial==1){
       CodigoBarra cm=new CodigoBarra();
       cm.setCod(cod);
       cm.setNum(num);
           CodigoBarraJpaController cmjc=new CodigoBarraJpaController(emf);
           cmjc.create(cm);
        codigoministerial=0;   
       }
       inicializarTabla();
        }else{JOptionPane.showMessageDialog(rootPane, "Los campos con (*) son obligatorios");}
        }else{JOptionPane.showMessageDialog(rootPane, "Ya existe un Producto con este Codigo");}
        }
        if(menu==2){
              List<Producto> listap=new FacadeProducto().buscarxCod(jTextField7.getText());
              int valida=listap.size();
          //    if(valida==0){         
        
             if(!jTextField1.getText().equals("")&&!jTextField2.getText().equals("")&&!jTextField3.getText().equals("")&&!jTextField4.getText().equals("")&&!jTextField5.getText().equals("")&&!jTextField7.getText().equals("")){         
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                Producto produ=prod;
                produ.setCod(jTextField7.getText());
                produ.setDescripcion(jTextField3.getText().toUpperCase());
                List<Proveedor> prov=new FacadeProveedor().buscarxnombre(jComboBox1.getSelectedItem().toString());
                produ.setProveedor(prov.get(0));
                List<TipoUnidades> tu=new FacadeTipoUnidades().buscarxnombre(jComboBox2.getSelectedItem().toString());
                prod.setUnidad(tu.get(0));
                prod.setTalle(jTextField6.getText().toUpperCase());
                Precio precio= produ.getPrecio();
                precio.setPrecio_real(Float.parseFloat(jTextField1.getText()));
                precio.setPrecio_contado(Float.parseFloat(jTextField2.getText()));
                //precio.setProducto(prod);
                List<Tarjeta> tarjera=new FacadeTarjeta().listar();
                precio.setTarjeta(tarjera);
                produ.setPrecio(precio);
                //Se agrega para saber si un producto del taller
                if(jCheckBox1.isSelected()){
                prod.setDetaller(1);
                }
                if(!jCheckBox1.isSelected()){
                prod.setDetaller(0);
                }
                    PrecioJpaController  prjc=new PrecioJpaController(emf);
                    ProductoJpaController pjc=new ProductoJpaController(emf);
                    prjc.edit(precio);
               pjc.edit(produ);
                 idprod=prod.getId();
                //chequear para entrar datos al almacen
                List<Almacen> al=new FacadeAlmacen().buscarxid(produ.getId());
               Almacen almacen= al.get(0);
                if(!jTextField4.getText().equals("")&& !jTextField5.getText().equals("")){
                almacen.setCantidad(jTextField4.getText());
                almacen.setAlerta(jTextField5.getText());
                almacen.setLocalizacion(jComboBox3.getSelectedItem().toString().toUpperCase());
                almacen.setProducto(produ);
                AlmacenJpaController ajc= new AlmacenJpaController(emf);
                    ajc.edit(almacen);
                 llenarTablaProd();
                }
                
                List<Localizacion> lista=new FacadeLocalizacion().buscarxAlmacen(String.valueOf(almacen.getId()),String.valueOf(almacen.getProducto().getId()));
                Localizacion loca=lista.get(0);
                System.out.println(loca.getDescripcion());
                float cantidad=Float.parseFloat(jTextField4.getText());
                loca.setCantidad(cantidad);
                LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                ljc.edit(loca);          
               JOptionPane.showMessageDialog(rootPane, "El registro se guardo con exito");
               limpiarCampos();
               if(codigoministerial==1){
                            CodigoBarra cm=new CodigoBarra();
                             cm.setCod(cod);
                             cm.setNum(num);
                             CodigoBarraJpaController cmjc=new CodigoBarraJpaController(emf);
                             cmjc.create(cm);
                               }
                inicializarTabla();
                this.dispose();
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
         }else{JOptionPane.showMessageDialog(rootPane, "Los campos con (*) son obligatorios");}
        //}else{JOptionPane.showMessageDialog(rootPane, "Ya existe un Producto con este Codigo");}
              }
        
        if(menu==3){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                Producto produ=prod;
                idprod=prod.getId();
                List<Almacen> listaal=new FacadeAlmacen().buscarxid(prod.getId());
                Almacen almacen=listaal.get(0);       
                AlmacenJpaController ajc=new AlmacenJpaController(emf);
                ajc.destroy(almacen.getId());
                ProductoJpaController pjc=new ProductoJpaController(emf);
                pjc.destroy(produ.getId());
                JOptionPane.showMessageDialog(rootPane, "El registro se borro");
                
                  List<Localizacion> lista=new FacadeLocalizacion().buscarxAlmacen(String.valueOf(almacen.getId()),String.valueOf(almacen.getProducto().getId()));
                  for(int i=0; i<lista.size();i++){
                  Localizacion loca=lista.get(0);
                  LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                  ljc.destroy(loca.getId());
                  }
               limpiarCampos();
               inicializarTabla();
               this.dispose();
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ejecutarReporteCB();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // jTextField7.setEnabled(false);
        codigoministerial=1;
        List<CodigoBarra> listap=new FacadeProducto().buscarxCodbarra("4242");
        int tamanio=listap.size();
        if(tamanio!=0){
        CodigoBarra codi=listap.get(0);
        int numero=codi.getNum();           
        cod="4242";
        num=numero+1;
        jTextField7.setText(cod+"-"+num);
        }if(tamanio==0){
        cod="4242";
        num=1;
        jTextField7.setText(cod+"-"+num);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
           float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
           float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
           float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
           float k = (float) evt.getKeyChar();
           char c =  evt.getKeyChar();
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        
     cargarCombos();
     llenarComboLocalizacion();
     codigoministerial=0;
     if(menu==1){
     jTextField1.setEnabled(true);
     jTextField2.setEnabled(true);
     jTextField3.setEnabled(true);
     jTextField4.setEnabled(true);
     jTextField5.setEnabled(true);
     jTextField6.setEnabled(true);
     jTextField7.setEnabled(true);
     jComboBox1.setEnabled(true);
     jTable2.setEnabled(false);
//     jButton1.setEnabled(true);
     jButton2.setEnabled(true);
     jButton3.setEnabled(true);
     jButton4.setEnabled(false);
     jCheckBox1.setEnabled(true);     
     llenarTablaProd();
     }
     if(menu==2){
     jTextField1.setEnabled(true);
     jTextField2.setEnabled(true);
     jTextField3.setEnabled(true);
     jTextField4.setEnabled(true);
     jTextField5.setEnabled(true);
     jTextField6.setEnabled(true);
     jTextField7.setEnabled(false);
     jComboBox1.setEnabled(true);
     jCheckBox1.setEnabled(true);
     jTable2.setEnabled(true);
//     jButton1.setEnabled(true);
     jButton2.setEnabled(true);
     jButton3.setEnabled(true);
     jButton4.setEnabled(true);
     llenarTablaProd();
     BuscarProducto ventana=new BuscarProducto(this, true);
     ventana.setVisible(true);
     prod=ventana.producto.getProducto();
     jComboBox1.setSelectedItem(prod.getProveedor().getNombre());
     jTextField3.setText(prod.getDescripcion());
     jTextField1.setText(String.valueOf(prod.getPrecio().getPrecio_real()));
     jTextField2.setText(String.valueOf(prod.getPrecio().getPrecio_contado()));
     List<Almacen> lista= new FacadeAlmacen().buscarxid(prod.getId());
     Almacen almacen=lista.get(0);
     jTextField4.setText(almacen.getCantidad());
     jTextField5.setText(almacen.getAlerta());
     jTextField6.setText(prod.getTalle());
     jComboBox3.setSelectedItem(almacen.getLocalizacion());;
     jTextField7.setText(prod.getCod());
     
     }
     if(menu==3){
     jTextField1.setEnabled(false);
     jTextField2.setEnabled(false);
     jTextField3.setEnabled(false);
     jTextField4.setEnabled(false);
     jTextField5.setEnabled(false);
     jTextField6.setEnabled(false);
     jTextField7.setEnabled(false);
     jComboBox1.setEnabled(false);
     jCheckBox1.setEnabled(false);
     jTable2.setEnabled(true);
//     jButton1.setEnabled(true);
     jButton2.setEnabled(true);
     jButton3.setEnabled(true);
     jButton4.setEnabled(true);
     llenarTablaProd();
      BuscarProducto ventana=new BuscarProducto(this, true);
     ventana.setVisible(true);
     prod=ventana.producto.getProducto();
     jComboBox1.setSelectedItem(prod.getProveedor().getNombre());
     jTextField3.setText(prod.getDescripcion());
     jTextField1.setText(String.valueOf(prod.getPrecio().getPrecio_real()));
     jTextField2.setText(String.valueOf(prod.getPrecio().getPrecio_contado()));
     List<Almacen> lista= new FacadeAlmacen().buscarxid(prod.getId());
     Almacen almacen=lista.get(0);
     jTextField4.setText(almacen.getCantidad());
     jTextField5.setText(almacen.getAlerta());
     jTextField6.setText(prod.getTalle());
     jComboBox3.setSelectedItem(almacen.getLocalizacion());
     jTextField7.setText(prod.getCod());
     }
    }
      private void cargarCombos() {
     DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
     List<Proveedor> lista;
     lista=new FacadeProveedor().listar();
     if(lista.get(0).getId()!=null){
      for(int i=0;  i < lista.size(); i++){
      Vector vector = new Vector();
      vector.add(lista.get(i).getNombre());
      modeloCombo.addElement(lista.get(i).getNombre());
     }
     jComboBox1.setModel(modeloCombo);            
    }
     
     DefaultComboBoxModel modeloCombo1 = new DefaultComboBoxModel();
     List<TipoUnidades> lista1;
     lista1=new FacadeTipoUnidades().listar();
     if(lista1.get(0).getId()!=null){
      for(int i=0;  i < lista1.size(); i++){
      Vector vector1 = new Vector();
      vector1.add(lista1.get(i).getDescripcion());
      modeloCombo1.addElement(lista1.get(i).getDescripcion());
     }
     jComboBox2.setModel(modeloCombo1);            
    }
    }
     public void llenarTabla(){
     EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
     DefaultTableModel modeloTabla=new DefaultTableModel();
     List<Tarjeta> lista=new FacadeTarjeta().listar();
     
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Tarjeta");
    modeloTabla.addColumn("Plan");
    modeloTabla.addColumn("Descuento");
    modeloTabla.addColumn("Precio");
    
    
    for (int i = 0; i < lista.size(); i++) {
      Vector vector = new Vector();
      vector.add(lista.get(i).getId());
      vector.add(lista.get(i).getNombre());
      vector.add(lista.get(i).getCant_cuotas());
      vector.add(lista.get(i).getDescuento());
      float variable=lista.get(i).getDescuento();
      float calculo=(Float.parseFloat(jTextField2.getText())*variable)/100;
      float preciot= Float.parseFloat(jTextField2.getText())-calculo;
      vector.add(preciot);
      modeloTabla.addRow(vector);
    }
//     jTable1.setModel(modeloTabla);
     
     }
     public void limpiarCampos(){
     jTextField1.setText("");
     jTextField2.setText("");
     jTextField3.setText("");
     jTextField4.setText("");
     jTextField5.setText("");
     jTextField6.setText("");
     jTextField7.setText("");
     jCheckBox1.setSelected(false);
     }
    public void llenarTablaProd(){
    EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
    List <Producto> listap=new FacadeProducto().listar();
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("Producto");
    modelo.addColumn("Talle");
    modelo.addColumn("Proveedor");
    modelo.addColumn("precio Compra");
    modelo.addColumn("precio Venta");
    for(int i=0; i<listap.size(); i++){
    Vector vector=new Vector();
    vector.add(listap.get(i).getId());
    vector.add(listap.get(i).getDescripcion());
    vector.add(listap.get(i).getTalle());
    vector.add(listap.get(i).getProveedor().getNombre());
    vector.add(listap.get(i).getPrecio().getPrecio_real());
    vector.add(listap.get(i).getPrecio().getPrecio_contado());    
    modelo.addRow(vector);
    }
    jTable2.setModel(modelo);
    }
    public void inicializarTabla(){
     EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
     DefaultTableModel modeloTabla=new DefaultTableModel();
     List<Tarjeta> lista=new FacadeTarjeta().listar();
     
    Vector<String> columnas = new Vector<String>();
    modeloTabla.addColumn("Id");
    modeloTabla.addColumn("Tarjeta");
    modeloTabla.addColumn("Plan");
    modeloTabla.addColumn("Descuento");
    modeloTabla.addColumn("Precio");
    //jTable1.setModel(modeloTabla);
    }
 private void llenarComboLocalizacion() {
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
     List<String> lista;
     lista=new FacadeLocalizacion().listardistintos1();
    
     for(int i=0;  i < lista.size(); i++){
      Vector vector = new Vector();
      vector.add(lista.get(i));
      modeloCombo.addElement(lista.get(i));
     }
     
     jComboBox3.setModel(modeloCombo);
     }

  private void ejecutarReporteCB() {
        try {
            
            Reporte reporte=new Reporte();
            reporte.ejecutarReporteCodBarraProducto(idprod);
        } catch (JRException ex) {
            Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JfProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  public void deshabilitarpizzeria(){
  jLabel6.setVisible(false);
  jTextField6.setVisible(false);
  jCheckBox1.setVisible(false);
  }
}
