/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.ClienteJpaController;
import Controladores.Cuenta_ClienteJpaController;
import Controladores.LocalizacionJpaController;
import Controladores.MesaJpaController;
import Controladores.MozoJpaController;
import Controladores.ProveedorJpaController;
import Controladores.TipoUnidadesJpaController;
import Controladores.Tipo_ClienteJpaController;
import Controladores.Tipo_DocJpaController;
import Controladores.UsuarioJpaController;
import Entidades.Almacen;
import Entidades.Cliente;
import Entidades.Cuenta_Cliente;
import Entidades.Localizacion;
import Entidades.Mesa;
import Entidades.Mozo;
import Entidades.Proveedor;
import Entidades.TipoUnidades;
import Entidades.Tipo_Cliente;
import Entidades.Tipo_Doc;
import Entidades.Usuario;
import Facade.FacadeAlmacen;
import Facade.FacadeLocalizacion;
import Facade.FacadeUsuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import org.apache.batik.i18n.Localizable;

/**
 *
 * @author Pablo
 */
public class JLogin extends javax.swing.JFrame {
 public static Usuario usu;
        
    /**
     * Creates new form JLogin
     */
    public JLogin() {
        initComponents();
          this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(JLogin.class, "JLogin.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(JLogin.class, "JLogin.jTextField1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(JLogin.class, "JLogin.jLabel2.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(JLogin.class, "JLogin.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(JLogin.class, "JLogin.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setText(org.openide.util.NbBundle.getMessage(JLogin.class, "JLogin.jPasswordField1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            List<Usuario> lista=new FacadeUsuario().CheckUsuario(jTextField1.getText(),jPasswordField1.getText());
        if(lista.size()!=0){
        usu=lista.get(0);
        Menu ventana=new Menu();
        ventana.setVisible(true);
        this.dispose();
        }
        if(lista.size()==0){
        JOptionPane.showMessageDialog(rootPane, "Nombre de Usuario o Contraseña Incorrecto");
        limpiarCampos();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void inicializarComponentes() {
        EstablecerSuperUsuario();
        CargarLocalizacion();
    }
    
     private void EstablecerSuperUsuario() {
        List<Usuario> list = new ArrayList<Usuario>();
        FacadeUsuario fa=new FacadeUsuario();
        list=fa.ObtenerID();
        if(list==null){
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
        Usuario usuario=new Usuario();
        usuario.setNombre("ADMIN");
        usuario.setPass("123");
        usuario.setTipo("ADMINISTRADOR");
        UsuarioJpaController ujc=new UsuarioJpaController(emf);
        ujc.create(usuario);
        CrearDatosIniciales();    
        }else{
         int tamaniolista=list.size()+1;       
        }
     }

    private void limpiarCampos() {
       jTextField1.setText("");
       jPasswordField1.setText("");
       
    }

    private void CrearDatosIniciales() {
    EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
        Tipo_Doc td=new Tipo_Doc();
        td.setDescripcion("DNI");
        Tipo_DocJpaController tdc=new Tipo_DocJpaController(emf);
        tdc.create(td);
        
        Tipo_Cliente tc=new Tipo_Cliente();
        tc.setDescripcion("COMUN");
        Tipo_ClienteJpaController tcc=new Tipo_ClienteJpaController(emf);
        tcc.create(tc);
        
        Cliente cliente=new Cliente();
        cliente.setApellido("CLIENTE");
        cliente.setNombre("GENERAL");
        cliente.setTipo_doc(td);
        cliente.setDoc("0");
        cliente.setTel("SIN ASIGNAR");
        cliente.setDomicilio("SIN ASIGNAR");
        cliente.setEmail("SIN ASIGNAR");
        cliente.setDescripcion(tc);
            Cuenta_Cliente cuenta=new Cuenta_Cliente();
            cuenta.setNombre(td.getDescripcion()+"0");
            cuenta.setEstado("SIN DEUDA");
            Cuenta_ClienteJpaController ccjp=new Cuenta_ClienteJpaController(emf);
            ccjp.create(cuenta); 
        cliente.setCuenta(cuenta);
        ClienteJpaController cjc=new ClienteJpaController(emf);
        cjc.create(cliente);
        
        TipoUnidades tu=new TipoUnidades();
        tu.setDescripcion("UNIDAD");
        TipoUnidadesJpaController tuc=new TipoUnidadesJpaController(emf);
        tuc.create(tu);
        
        Proveedor pro=new Proveedor();
        pro.setNombre("GENERAL");
        pro.setDoc("0");
        pro.setCuit("0");
        pro.setDireccion("SIN ASIGNAR");
        pro.setEmail("SIN ASIGNAR");
        pro.setRepresentante("GENERAL");
        pro.setTel("SIN ASIGNAR");
        pro.setTipodoc(td);
        ProveedorJpaController pjc=new ProveedorJpaController(emf);
        pjc.create(pro);
        
        Mozo mozo=new Mozo();
        mozo.setApellido("GENERAL");
        mozo.setNombre("");
        mozo.setDni("0");
        mozo.setDomicilio("");
        mozo.setTelefono("0");
        MozoJpaController mjc=new MozoJpaController(emf);
        mjc.create(mozo);
        
        Mesa mesa=new Mesa();
        mesa.setCerrado(1);
        mesa.setDescripcion("GENERAL");
        mesa.setNumero(0);
        MesaJpaController mejc=new MesaJpaController(emf);
        mejc.create(mesa);
        
            String nombre="NEGOCIO";
            boolean valida=new FacadeLocalizacion().validarLocalizacion(nombre);
            if(!valida){
            //EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
            Localizacion localizacion=new Localizacion();
            localizacion.setDescripcion(nombre);
            localizacion.setCantidad(0);
                LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                ljc.create(localizacion);
            }
    }

    private void CargarLocalizacion() {
      List<Localizacion> list = new ArrayList<Localizacion>();
        FacadeLocalizacion fa=new FacadeLocalizacion();
        list=fa.ObtenerID();
        if(list==null){
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaalmacen=new ArrayList<Almacen>();
        listaalmacen=new FacadeAlmacen().listar();
        if(listaalmacen.size()!=0){
        for(int i=0; i< listaalmacen.size();i++){
        Localizacion localizacion=new Localizacion();
        localizacion.setCantidad(Integer.parseInt(listaalmacen.get(i).getCantidad()));
        localizacion.setDescripcion(listaalmacen.get(i).getLocalizacion());
        localizacion.setId_almacen(String.valueOf(listaalmacen.get(i).getId()));
        localizacion.setId_producto(String.valueOf(listaalmacen.get(i).getProducto().getId()));
            LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
            ljc.create(localizacion);
        }
        }
        }else{
         int tamaniolista=list.size()+1;       
        }
    }
}
