/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.AlmacenJpaController;
import Controladores.Cuenta_ClienteJpaController;
import Controladores.LocalizacionJpaController;
import Controladores.PagoClienteJpaController;
import Controladores.VentaJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Almacen;
import Entidades.Cliente;
import Entidades.Cuenta_Cliente;
import Entidades.Datos_Contado;
import Entidades.Datos_Cuenta_Corriente;
import Entidades.Datos_Tarjeta;
import Entidades.Datos_cheque;
import Entidades.Detalle_Cuenta_Cliente;
import Entidades.Detalle_Venta;
import Entidades.Detalle_tipo_venta;
import Entidades.Localizacion;
import Entidades.PagoCliente;
import Entidades.Producto;
import Entidades.Tipo_Pago;
import Entidades.Tipo_Venta;
import Entidades.Venta;
import Facade.FacadeAlmacen;
import Facade.FacadeCliente;
import Facade.FacadeCuentaCliente;
import Facade.FacadeLocalizacion;
import Facade.FacadeProducto;
import static Vistas.JfVenta.tipopago;
import static Vistas.JfVenta.venta;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo
 */
public class ventaTaller extends javax.swing.JFrame {
 Almacen productoAlmacen;
 Venta venta;
 DefaultTableModel modelo=new DefaultTableModel();
  DefaultTableModel modelo2=new DefaultTableModel();
  static float totalfiltrado;
  Cliente cliente;
//Datos que vienen de la ventana Forma de pago
     List<Datos_cheque> listacheques=new ArrayList<Datos_cheque>();
     List<Datos_Tarjeta> listatar=new ArrayList<Datos_Tarjeta>();
     List<Datos_Cuenta_Corriente> listacuentac=new ArrayList<Datos_Cuenta_Corriente>();
     String entrega;
     Datos_Contado contado=new Datos_Contado();
     static Tipo_Pago tipopago;
     int facturaemitida=0;
     /**
     * Creates new form ventaTaller
     */
    public ventaTaller() {
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel3.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField1.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel4.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField2.text")); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel5.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField3.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel6.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField4.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel7.text")); // NOI18N

        jTextField5.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField5.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel8.text")); // NOI18N

        jTextField6.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField6.text")); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel18.text")); // NOI18N

        jTextField14.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField14.text")); // NOI18N

        jLabel20.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel20.text")); // NOI18N

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel21.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel21.text")); // NOI18N

        jTextField16.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField16.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))
                                .addGap(10, 10, 10)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel9.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel10.text")); // NOI18N

        jTextField7.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField7.text")); // NOI18N

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton5.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel11.text")); // NOI18N

        jTextField8.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField8.text")); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton6.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel12.text")); // NOI18N

        jTextField9.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField9.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel13.text")); // NOI18N

        jTextField10.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField10.text")); // NOI18N
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jLabel14.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel14.text")); // NOI18N

        jTextField11.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField11.text")); // NOI18N
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel15.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel15.text")); // NOI18N

        jTextField12.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField12.text")); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jButton7.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        jButton8.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton8.text")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel19.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel19.text")); // NOI18N

        jTextField15.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField15.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addGap(285, 285, 285))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8)
                        .addComponent(jButton7))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel16.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel16.text")); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel17.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel17.text")); // NOI18N

        jTextField13.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField13.text")); // NOI18N

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton9.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton9.text")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton10.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton10.text")); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jButton11.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton11.text")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel22.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jLabel22.text")); // NOI18N

        jTextField17.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jTextField17.text")); // NOI18N
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });

        jButton12.setText(org.openide.util.NbBundle.getMessage(ventaTaller.class, "ventaTaller.jButton12.text")); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jLabel22)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!jTextField2.getText().equals("")){
        buscarxcodigo();
        }
        if(jTextField2.getText().equals("")){
        inicializarTablaProductosStock();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jTextField1.getText().equals("")){
        buscarProducto();
        }
        if(jTextField1.getText().equals("")){
        inicializarTablaProductosStock();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(!jTextField7.getText().equals("")){
        buscarProductoTaller();
        }
        if(jTextField7.getText().equals("")){
        inicializarTablaProductosTaller();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(!jTextField8.getText().equals("")){
        buscarxcodigoTaller();
        }
        if(jTextField8.getText().equals("")){
        inicializarTablaProductosTaller();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      if(jTable1.getSelectedRow()!=-1){
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      productoAlmacen=new AlmacenJpaController(emf).findAlmacen(valor);
      jTextField3.setText(productoAlmacen.getProducto().getDescripcion());
      jTextField4.setText(productoAlmacen.getProducto().getProveedor().getNombre());
      jTextField14.setText(String.valueOf(productoAlmacen.getProducto().getPrecio().getPrecio_contado()));
      jTextField5.setText(String.valueOf(productoAlmacen.getCantidad()));
      llenarComboLocalizacion();
      //Pone las unidades en el area en caso de no haber echo click en el jcombo
        List<Localizacion> lista=new FacadeLocalizacion().buscarxdes(jComboBox1.getSelectedItem().toString(),String.valueOf(productoAlmacen.getId()));
        if(lista.size()!=0){
        Localizacion loc=lista.get(0);
        jTextField16.setText(String.valueOf(loc.getCantidad()));
        }
      
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
      if(jTable2.getSelectedRow()!=-1){
      EntityManagerFactory emf = Persistence.createEntityManagerFactory("pintureriaPU");  
      String valorTabla=(jTable2.getValueAt(jTable2.getSelectedRow(),0)).toString();
      Long valor=Long.parseLong(valorTabla);
      productoAlmacen=new AlmacenJpaController(emf).findAlmacen(valor);
      jTextField9.setText(productoAlmacen.getProducto().getDescripcion());
      jTextField12.setText(productoAlmacen.getProducto().getUnidad().getDescripcion());
      jTextField10.setText(String.valueOf(productoAlmacen.getProducto().getPrecio().getPrecio_contado()));
      jTextField15.setText(String.valueOf(productoAlmacen.getCantidad()));
      //llenarComboLocalizacion();
      
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       if(productoAlmacen!=null && !jTextField6.getText().equals("")){ 
       float unidadesDisponibles=Float.parseFloat(jTextField5.getText());
       float unidadesRequeridas=Float.parseFloat(jTextField6.getText());
       
       //Pone las unidades en el area en caso de no haber echo click en el jcombo
        List<Localizacion> lista=new FacadeLocalizacion().buscarxdes(jComboBox1.getSelectedItem().toString(),String.valueOf(productoAlmacen.getId()));
        if(lista.size()!=0){
        Localizacion loc=lista.get(0);
        jTextField16.setText(String.valueOf(loc.getCantidad()));
        }
       float unidaesenArea=Float.parseFloat(jTextField16.getText());
        if(unidadesRequeridas <= unidadesDisponibles){
         if(unidadesRequeridas<=unidaesenArea){   
       Vector vector=new Vector();
       vector.add(productoAlmacen.getId());
       vector.add(productoAlmacen.getProducto().getDescripcion());
      // vector.add(productoAlmacen.getProducto().getTalle());
       vector.add(productoAlmacen.getProducto().getProveedor().getNombre());
       vector.add(productoAlmacen.getProducto().getPrecio().getPrecio_contado());
       vector.add(jTextField6.getText());
       vector.add(productoAlmacen.getLocalizacion());
       modelo2.addRow(vector);
       jTable3.setModel(modelo2);
       limpiarCampos();
       calcularTotal();
        }else{JOptionPane.showMessageDialog(rootPane, "Las unidades Requiridas son mayores a las disponible en esa Area");}
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Las unidades disponibles no cubren la demanda");
        }
         } else {JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un producto y especificar la cantidad a vender");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       int index=jTable3.getSelectedRow();
       modelo2.removeRow(index);
       jTable3.setModel(modelo2);
       limpiarCampos();
       calcularTotal();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton9.setEnabled(true);
        if(productoAlmacen!=null && !jTextField11.getText().equals("")){ 
       float unidadesDisponibles=Float.parseFloat(jTextField15.getText());
       float unidadesRequeridas=Float.parseFloat(jTextField11.getText());
       
       //Pone las unidades en el area en caso de no haber echo click en el jcombo
       // List<Localizacion> lista=new FacadeLocalizacion().buscarxdes("NEGOCIO",String.valueOf(productoAlmacen.getId()));
        //if(lista.size()!=0){
        //Localizacion loc=lista.get(0);
        //jTextField9.setText(String.valueOf(loc.getCantidad()));
        //}
       float unidaesenArea=Float.parseFloat(jTextField15.getText());
        if(unidadesRequeridas <= unidadesDisponibles){
         if(unidadesRequeridas<=unidaesenArea){   
       Vector vector=new Vector();
       vector.add(productoAlmacen.getId());
       vector.add(productoAlmacen.getProducto().getDescripcion());
      // vector.add(productoAlmacen.getProducto().getTalle());
       vector.add(productoAlmacen.getProducto().getProveedor().getNombre());
       vector.add(jTextField10.getText());
       //vector.add(productoAlmacen.getProducto().getPrecio().getPrecio_contado());
       vector.add(jTextField11.getText());
       vector.add(productoAlmacen.getLocalizacion());
       modelo2.addRow(vector);
       jTable3.setModel(modelo2);
       limpiarCampos2();
       calcularTotal();
        }else{JOptionPane.showMessageDialog(rootPane, "Las unidades Requiridas son mayores a las disponible en esa Area");}
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Las unidades disponibles no cubren la demanda");
        }
         } else {JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un producto y especificar la cantidad a vender");
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       int index=jTable3.getSelectedRow();
       modelo2.removeRow(index);
       jTable3.setModel(modelo2);
       limpiarCampos2();
       calcularTotal();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        List<Localizacion> lista=new FacadeLocalizacion().buscarxdes(jComboBox1.getSelectedItem().toString(),String.valueOf(productoAlmacen.getId()));
        if(lista.size()!=0){
        Localizacion loc=lista.get(0);
        jTextField16.setText(String.valueOf(loc.getCantidad()));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          if(Menu.opcion==1){
          if(cliente!=null){    
       //  if(jComboBox1.getSelectedItem().equals("TARJETA")){    
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");        
        Venta venta=new Venta();
        venta.setFecha(jXDatePicker1.getDate());
        venta.setCliente(cliente);
        venta.setMonto(Float.parseFloat(jTextField13.getText()));
        venta.setAnulacion("NO");
        venta.setPagoRegistrado("SI");
        venta.setPorcentaje_descuento(Integer.parseInt(jTextField17.getText()));
        venta.setUsu(JLogin.usu);
        //venta.setDescripcion(jComboBox1.getSelectedItem().toString());
        /// cargar detalle de Venta
        ArrayList<Detalle_Venta> ldv = new ArrayList<Detalle_Venta>();
        for(int i=0; i< jTable3.getRowCount(); i++ ){
        Detalle_Venta dv=new Detalle_Venta();    
        List<Producto> lp=new FacadeProducto().buscarxnombre(String.valueOf(jTable3.getValueAt(i, 1)).toUpperCase());
        dv.setProducto(lp.get(0));
        dv.setCantidad(Float.parseFloat(jTable3.getValueAt(i, 4).toString()));
        dv.setMonto(Float.valueOf(jTable3.getValueAt(i, 3).toString()));
        ldv.add(dv);
        }
        venta.setDetalle_venta(ldv);
        //llenar Tipo de venta
        Tipo_Venta tv= new Tipo_Venta();
        /*tv.setAnticipo(Float.parseFloat(jTextField15.getText()));
        tv.setCant_cuotas(Integer.parseInt(jTextField8.getText()));
        tv.setTipo(jComboBox1.getSelectedItem().toString());
        tv.setTajeta(tarjeta);
        tv.setDescuento(tarjeta.getDescuento());*/
        //llenar tipo de pago
        tipopago=new Tipo_Pago();
        //modifique para jimi comente y deje solo contado
        //int tamaniolc=listacheques.size();
        //if(tamaniolc!=0){
        //tipopago.setCheques(listacheques);
        //}
        //if(contado!=null){
        //tipopago.setContado(contado);
        //}
        //int tamaniocc=listacuentac.size();
        //if(tamaniocc!=0){
        //tipopago.setCuentacorrientes(listacuentac);
        //}
        //int tamaniot=listatar.size();
        //if(tamaniot!=0){
        //tipopago.setTarjetas(listatar);
        //}
        if(!jTextField13.equals("")){
        contado.setEntrega(Float.parseFloat(jTextField13.getText()));
        tipopago.setContado(contado);
        }
        //hasta aca
        //Agrego para jimmi lo del combo 
        venta.setDescripcion("CONTADO");
        tv.setTipo_pago(tipopago);
        ArrayList<Detalle_tipo_venta> ldtv=new ArrayList<Detalle_tipo_venta>();
        
              venta.setTipoventa(tv);
        VentaJpaController vjp= new VentaJpaController(emf);
        vjp.create(venta);
        
        // Modificar Almacen y los productos en el area
        for(int i=0; i< jTable3.getRowCount(); i++ ){
            try {
                Almacen almacen= new Almacen();
                //List<Almacen> la=new FacadeAlmacen().buscarxnombre(String.valueOf(jTable3.getValueAt(i, 1)).toUpperCase());
                List<Almacen> la=new FacadeAlmacen().buscarxid(Long.parseLong(jTable3.getValueAt(i, 0).toString()));
                almacen=la.get(0);
                float cantalmacen=Float.parseFloat(la.get(0).getCantidad());
                float cantvendida=Float.parseFloat(jTable3.getValueAt(i, 4).toString());
                almacen.setProducto(la.get(0).getProducto());
                almacen.setCantidad(String.valueOf(cantalmacen-cantvendida));
                almacen.setAlerta(la.get(0).getAlerta());
                almacen.setLocalizacion(la.get(0).getLocalizacion());
                AlmacenJpaController ajp=new AlmacenJpaController(emf);
                ajp.edit(almacen);
                
                Localizacion lo= new Localizacion();
                //List<Localizacion> llo=new FacadeLocalizacion().buscarxdes(jTable3.getValueAt(i, 5).toString());
                List<Localizacion> llo=new FacadeLocalizacion().buscarxdes(jTable3.getValueAt(i, 5).toString(),jTable3.getValueAt(i, 0).toString());
                //lo=llo.get(0);
                
                if(llo.size()!=0)
                {lo=llo.get(0);}
                if(llo.size()==0){
                lo=new Localizacion();
                lo.setCantidad(Float.parseFloat(almacen.getCantidad()));
                lo.setDescripcion(jTable3.getValueAt(i, 5).toString());
                lo.setId_almacen(String.valueOf(almacen.getId()));
                lo.setId_producto(String.valueOf(almacen.getProducto().getId()));
                LocalizacionJpaController ljc= new LocalizacionJpaController(emf);
                ljc.create(lo);
                }
                
                float cantidadlocal=lo.getCantidad();
                lo.setCantidad(cantidadlocal-cantvendida);
                LocalizacionJpaController ljc= new LocalizacionJpaController(emf);
                ljc.edit(lo);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // Actualizar la Cuenta del cliente (se actualiza cuando el tipo de pago pertenece a Cuenta corriente)
        if(listacuentac.size()!=0){
            try {
                Cuenta_Cliente cuenta=new Cuenta_Cliente();
                List<Cuenta_Cliente> lista=new FacadeCuentaCliente().buscarxdoc(cliente.getId());
                cuenta=lista.get(0);
                ArrayList<Detalle_Cuenta_Cliente> listacuenta=new ArrayList<Detalle_Cuenta_Cliente>();
                      //for(int i=0; i< jTable3.getRowCount();i++){
                      for(int i=0; i< 1;i++){
                   
                        Detalle_Cuenta_Cliente dtc=new Detalle_Cuenta_Cliente();
                        //dtc.setNro_cuota(Integer.parseInt(jTable3.getValueAt(i, 0).toString()));
                        dtc.setNro_cuota(listacuentac.get(i).getNro_cuota());
                        //dtv.setFecha_pago();
                        //SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                        //Date nuevaFecha = null;
                        //nuevaFecha = formatoFecha.parse(jTable3.getValueAt(i,1).toString());
                        Date nuevaFecha = listacuentac.get(i).getFecha_pago();
                        dtc.setFecha_vencimiento(nuevaFecha);
                        //dtc.setMonto_cuota(Float.parseFloat(jTable3.getValueAt(i, 2).toString()));
                        dtc.setMonto_cuota(listacuentac.get(i).getMonto_cuota());
                        //dtc.setEstado(jTable3.getValueAt(i, 3).toString());
                        dtc.setEstado(listacuentac.get(i).getEstado());
                        dtc.setVenta(venta);
                        //dtc.setCantidad_cuota(Integer.parseInt(jTextField8.getText()));
                        dtc.setCantidad_cuota(listacuentac.get(i).getCantidad_cuotas());
                        //dtc.setTipo_pago(venta.getTipoventa().getTipo());
                        dtc.setTipo_pago("Cuenta Corriente");
                        dtc.setAnulacion("NO");
                        listacuenta.add(dtc);
                   
                  }
                        cuenta.setDetalle(listacuenta);
                        
                        Cuenta_ClienteJpaController ccjc=new Cuenta_ClienteJpaController(emf);
                        ccjc.edit(cuenta);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
        JOptionPane.showMessageDialog(rootPane, "La operacion se Realizo con exito");
        jButton11.setEnabled(true);
        jButton9.setEnabled(false);
        //Agrego para Jimmi para q se registre el pago de la venta desde aca
         PagoCliente registrarPago=new PagoCliente();
         registrarPago.setAnulacion("NO");
         registrarPago.setFechapago(jXDatePicker1.getDate());
         registrarPago.setMonto(Float.parseFloat(jTextField13.getText()));
         registrarPago.setVenta(venta);
         PagoClienteJpaController pjc=new PagoClienteJpaController(emf);
         pjc.create(registrarPago);
        //this.dispose();
           // Agrego para cargar la tabla de vuelta actualizada con el stock
        if(!jTextField1.getText().equals("")&&jTextField2.getText().equals("")){
        buscarProducto();
        }
        if(jTextField1.getText().equals("")&&jTextField2.getText().equals("")){
        inicializarTablaProductosStock();
        }
        if(jTextField1.getText().equals("")&&!jTextField2.getText().equals("")){
        buscarxcodigo();
        }
        //para tabla Stock
        inicializarTablaProductosTaller();
        bloquearBotones();
        }else {JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un cliente para la venta");
        }
        }
        if(Menu.opcion==2){
            if(venta.getPagoRegistrado().equals("SI")){
            try {
                EntityManagerFactory emf=Persistence.createEntityManagerFactory("pintureriaPU");
                venta.setAnulacion("SI");
                //modificar la cuenta del cliente anular la venta
                 
                VentaJpaController vjc=new VentaJpaController(emf);
                vjc.edit(venta);
                
                //Actualizar el almacen con el regreso de los elementos de la venta
                // 3 precio 4 cantidad
                for(int i=0; i<venta.getDetalle_venta().size();i++){
                List<Almacen>lista=new FacadeAlmacen().buscarxid(venta.getDetalle_venta().get(i).getProducto().getId());
                Almacen almacen=lista.get(0);
                // cantidad a devolver
                float cantidaddevol=venta.getDetalle_venta().get(i).getCantidad();
                //cantidad en Stock
                float cantidadStock=Float.parseFloat(almacen.getCantidad());
                almacen.setCantidad(String.valueOf(cantidadStock+cantidaddevol));
                AlmacenJpaController ajc=new AlmacenJpaController(emf);
                ajc.edit(almacen);
                
                //Devuelve en la localizacion el primer q encuentre con el id de almacen
                List<Localizacion> listalocalizacion=new FacadeLocalizacion().buscarxAlmance(String.valueOf(almacen.getId()));
                Localizacion loc=listalocalizacion.get(0);
                float cantidadenzona=loc.getCantidad();
                loc.setCantidad(cantidadenzona+cantidaddevol);
                LocalizacionJpaController ljc=new LocalizacionJpaController(emf);
                
                }
                
                JOptionPane.showMessageDialog(rootPane, "la Venta fue anulada");
                this.dispose();
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JfVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
         } else{JOptionPane.showMessageDialog(rootPane, "La venta no puede ser anulada por q su pago ya fue Registrado");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         if(facturaemitida==0){
        JfFactura ventana=new JfFactura();
        ventana.setVisible(true);
        facturaemitida=ventana.emitido;
        jButton11.setEnabled(false);
        }
        if(facturaemitida==1){
        jButton11.setEnabled(false);
        }
         //JfFactura ventana=new JfFactura();
        //ventana.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(!jTextField17.getText().equals("0") && !jTextField17.getText().equals("")){
        int porcentaje=Integer.parseInt(jTextField17.getText());
        float total=Float.parseFloat(jTextField13.getText());
        float resultporc=(total*porcentaje)/100;
        float toltalnuevo=total-resultporc;
        jTextField13.setText(String.valueOf(toltalnuevo));
        }else{
        jTextField17.setText("0");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
        // TODO add your handling code here:
      float k = (float) evt.getKeyChar(); 
      if (k >= 97 && k <= 122 || k >= 65 && k <= 90) { 
      evt.consume(); 
      JOptionPane.showMessageDialog(null, "No puede ingresar Letras!!!", "Error Datos", JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_jTextField17KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventaTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventaTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventaTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventaTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventaTaller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
    if(Menu.opcion==1){
        jTextField1.setEnabled(true);
    jTextField2.setEnabled(true);
    jXDatePicker1.setFormats("dd/MM/yyyy");
    jXDatePicker1.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(true);
    jTextField7.setEnabled(true);
    jTextField8.setEnabled(true);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(true);
    jTextField11.setEnabled(true);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
    jTextField14.setEnabled(false);
    jTextField15.setEnabled(false);
    jTextField16.setEnabled(false);
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);
    jButton5.setEnabled(true);
    jButton6.setEnabled(true);
    jButton7.setEnabled(true);
    jButton8.setEnabled(true);
    jButton9.setEnabled(false);
    jButton10.setEnabled(true);
    jTextField17.setEnabled(true);
    jTextField17.setText("0");
    //Inicializar Fecha de hoy
    Date hoy=new Date();
    jXDatePicker1.setDate(hoy);
    inicializarTablaProductosStock();
    inicializarTablaProductosTaller();
    inicializarTablaDetalle();
    llenarClienteGeneral();    
    }

        if(Menu.opcion==2){
    jTextField1.setEnabled(false);
    jTextField2.setEnabled(false);
    jXDatePicker1.setFormats("dd/MM/yyyy");
    jXDatePicker1.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField4.setEnabled(false);
    jTextField5.setEnabled(false);
    jTextField6.setEnabled(false);
    jTextField7.setEnabled(false);
    jTextField8.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
    jTextField12.setEnabled(false);
    jTextField13.setEnabled(false);
    jTextField14.setEnabled(false);
    jTextField15.setEnabled(false);
    jTextField16.setEnabled(false);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(false);
    jButton7.setEnabled(false);
    jButton8.setEnabled(false);
    jButton9.setEnabled(true);
    jButton10.setEnabled(true);
    //Inicializar Fecha de hoy
    Date hoy=new Date();
    jXDatePicker1.setDate(hoy);
    inicializarTablaProductosStock();
    inicializarTablaProductosTaller();
    inicializarTablaDetalle();
    BuscarVenta ventana=new BuscarVenta(this, true);
    ventana.setVisible(true);
    venta=ventana.venta;
    CargarDatos();
    }
    }

    private void inicializarTablaProductosStock() {
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().listar(0);
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
         modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
       // modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
        //vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    
    }

    private void inicializarTablaProductosTaller() {
     EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().listar(1);
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        //modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
       // modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        //vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
        //vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable2.setModel(modeloTabla);   
    }
    
    private void buscarProducto() {
       EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().buscarxnombre(jTextField1.getText().toUpperCase(),0);
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        //modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
       // vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    }
    
    private void buscarxcodigo() {
       EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().buscarxcod(jTextField2.getText(),0);
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        //modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
        //vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    }
     private void buscarProductoTaller() {
       EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().buscarxnombre(jTextField7.getText().toUpperCase(),1);
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        //modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        //modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        //vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
       // vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable2.setModel(modeloTabla);
    }
     private void buscarxcodigoTaller() {
       EntityManagerFactory emf= Persistence.createEntityManagerFactory("pintureriaPU");
        List<Almacen> listaproducto= new FacadeAlmacen().buscarxcod(jTextField8.getText(),1);
        DefaultTableModel modeloTabla=new DefaultTableModel();
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Producto");
        //modeloTabla.addColumn("Talle");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Unidades Disponibles");
        //modeloTabla.addColumn("Localizacion");
        
        
        for(int i=0; i<listaproducto.size(); i++){
        Vector vector=new Vector();
        vector.add(listaproducto.get(i).getId());
        vector.add(listaproducto.get(i).getProducto().getDescripcion());
        //vector.add(listaproducto.get(i).getProducto().getTalle());
        vector.add(listaproducto.get(i).getProducto().getProveedor().getNombre());
        vector.add(listaproducto.get(i).getProducto().getPrecio().getPrecio_contado());
        vector.add(listaproducto.get(i).getCantidad());
        //vector.add(listaproducto.get(i).getLocalizacion());
        modeloTabla.addRow(vector);
        }
        jTable1.setModel(modeloTabla);
    }
       public void inicializarTablaDetalle(){
       modelo2.addColumn("Id");
       modelo2.addColumn("Producto");
       //modelo2.addColumn("Talle");
       modelo2.addColumn("Proveedor");
       modelo2.addColumn("Precio");
       modelo2.addColumn("Cantidad");
       modelo2.addColumn("Localizacion");
       jTable3.setModel(modelo2);
    }
    private void calcularTotal() {
    float total=0;    
    for(int i=0; i<jTable3.getRowCount();i++){
    float precio= Float.parseFloat(jTable3.getValueAt(i, 3).toString());
    float cantidad=Float.parseFloat(jTable3.getValueAt(i, 4).toString());
    float calculo= precio*cantidad;
    total=total+calculo;
    }
    jTextField13.setText(String.valueOf(total));
      if(!jTextField17.getText().equals("0") && !jTextField17.getText().equals("")){
        int porcentaje=Integer.parseInt(jTextField17.getText());
        float totalp=Float.parseFloat(jTextField13.getText());
        float resultporc=(totalp*porcentaje)/100;
        float toltalnuevo=total-resultporc;
        jTextField13.setText(String.valueOf(toltalnuevo));
        }else{
        jTextField17.setText("0");
        }
    }

    private void limpiarCampos() {
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField14.setText("");
    jTextField16.setText("");
    }
    private void limpiarCampos2() {
    jTextField9.setText("");
    jTextField10.setText("");
    jTextField11.setText("");
    jTextField12.setText("");
    jTextField15.setText("");
    }
     private void llenarComboLocalizacion() {
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
     List<Localizacion> lista;
     lista=new FacadeLocalizacion().buscarxAlmance(String.valueOf(productoAlmacen.getId()));
     if(lista.get(0).getId()!=null){
     for(int i=0;  i < lista.size(); i++){
      Vector vector = new Vector();
      vector.add(lista.get(i).getDescripcion());
      modeloCombo.addElement(lista.get(i).getDescripcion());
     }
     
     jComboBox1.setModel(modeloCombo);
     }  
    }
     private void llenarClienteGeneral() {
    List<Cliente> lcliente=new FacadeCliente().buscarxnombre("CLIENTE", "GENERAL");
    cliente=lcliente.get(0);
    //jTextField11.setText(cliente.getApellido()+""+cliente.getNombre());
    //jButton9.setVisible(false);
    //jLabel10.setVisible(false);
    }

    private void CargarDatos() {
       Date d=venta.getFecha(); 
       jXDatePicker1.setDate(d);
     for(int i=0; i < venta.getDetalle_venta().size(); i++){
       Vector vector=new Vector();  
       vector.add(venta.getDetalle_venta().get(i).getProducto().getId());
       vector.add(venta.getDetalle_venta().get(i).getProducto().getDescripcion());
       //vector.add(venta.getDetalle_venta().get(i).getProducto().getTalle());
       vector.add(venta.getDetalle_venta().get(i).getProducto().getProveedor().getNombre());
       vector.add(venta.getDetalle_venta().get(i).getMonto());
       vector.add(venta.getDetalle_venta().get(i).getCantidad());
       modelo2.addRow(vector);
     }
     jTable3.setModel(modelo2);
     
    //llenar Cliente
     //jTextField11.setText(venta.getCliente().getNombre());     
     jTextField17.setText(String.valueOf(venta.getPorcentaje_descuento()));

      calcularTotal();
    /*
     // Tipo de venta
     jComboBox1.setSelectedItem(venta.getTipoventa().getTipo());
     if(!venta.getTipoventa().getTajeta().getNombre().equals("")){
      jComboBox2.setSelectedItem(venta.getTipoventa().getTajeta().getNombre());
      jTextField10.setText(String.valueOf(venta.getTipoventa().getTajeta().getCant_cuotas()));
      jTextField8.setText(String.valueOf(venta.getTipoventa().getCant_cuotas()));
      jTextField15.setText(String.valueOf(venta.getTipoventa().getAnticipo()));
     }
        calcularTotal();
        
         float anticipo=Float.parseFloat(jTextField15.getText());
        jTextField7.setText(String.valueOf(Float.parseFloat(jTextField7.getText())-anticipo));
        float monto= Float.parseFloat(jTextField7.getText());
        int descuento=tarjeta.getDescuento();
        float porcentaje= (monto*descuento)/100;
        float total= (monto-porcentaje);
        float mon=total/Integer.parseInt(jTextField8.getText());
        jTextField9.setText(String.valueOf(mon));
        llenarTablaCuotas();
    */ 
    }
   public void bloquearBotones(){
   jButton1.setEnabled(false);
   jButton2.setEnabled(false);
   jButton3.setEnabled(false);
   jButton4.setEnabled(false);
   jButton5.setEnabled(false);
   jButton6.setEnabled(false);
   jButton7.setEnabled(false);
   jButton8.setEnabled(false);
   jButton9.setEnabled(false);
   jButton10.setEnabled(true);
   jButton11.setEnabled(true);
   jButton12.setEnabled(false);
   jTextField1.setEnabled(false);
   jTextField2.setEnabled(false);
   jTextField6.setEnabled(false);
   jTextField7.setEnabled(false);
   jTextField8.setEnabled(false);
   jTextField10.setEnabled(false);
   jTextField11.setEnabled(false);
   jTextField17.setEnabled(false);
   
   }
}
